/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
import React from 'react';
import * as b from '@clutch-creator/bridge';
import Grid from '../Grid';
import Typography from '../Typography';
import Text from '@clutch-marketplace/web-elements/dist/cjs/components/Text';
import Hook from '@clutch-marketplace/logic/dist/cjs/components/Hook';
import MediaScrollHookBaseHookModule from './logic/mediaScrollHook/base-hookmodule.js';
import Box from '../Box';
import Icon from '../Icon';
import CardMediaHomepage from '../Card - Media Homepage';
import CardHomepageEndCard from '../Card - Homepage End Card';

export default (props) => {
    const [report, getKey] = b.useReport(props);
    const { variants } = props;
    const variables = {};
  
    const rs = report(null, '17c901642bb14c88a0033242', 'COMPOSITION', props, variables);
  
    return ([
      <Grid
        key='grid-media-cards'
        variants={b.getVariants(undefined)}
        container={true}
        sx={{
          mb: 3,
        }}
        direction={'column'}
        data-d={getKey(rs, '17c9015809214c88a0033239')}
      >
        <Grid
          key='grid-72'
          variants={b.getVariants(undefined)}
          item={true}
          container={true}
          justifyContent={'space-between'}
          alignItems={'center'}
          data-d={getKey(rs, '17c99fe8ddb14c88a00330df')}
        >
          <Grid
            key='grid-96'
            variants={b.getVariants(undefined)}
            item={true}
            data-d={getKey(rs, '17c99fe8ddb14c88a00330e3')}
          >
            <Typography
              key='typography-7'
              variants={b.getVariants(undefined)}
              gutterBottom={false}
              variant={'h5'}
              sx={{
                fontWeight: '500',
                color: 'primary.main',
                fontSize: '1.75rem',
                lineHeight: {
                xs: '1.5',
                md: '1.75',
              },
              }}
              data-d={getKey(rs, '17c9a09d4a714c88a003311a')}
            >
              <Text
                key='default-text-47'
                variants={b.getVariants(undefined)}
                className={b.getUniqueClassName()}
                style={undefined}
                text={'Media'}
                tag={'span'}
                data-d={getKey(rs, '17c9a09d4a714c88a003311b')}
              />
            </Typography>
          </Grid>
          <Grid
            key='grid-73'
            variants={b.getVariants(undefined)}
            item={true}
            data-d={getKey(rs, '17c99fe8ddb14c88a00330e0')}
          >
            <Typography
              key='typography-23'
              variants={b.getVariants(undefined)}
              gutterBottom={false}
              variant={'subtitle2'}
              sx={{
                fontWeight: '500',
                ':hover': {
                color: 'primary.dark',
              },
                color: 'primary.main',
              }}
              data-d={getKey(rs, '17c99fe8ddb14c88a00330e1')}
            >
              <Text
                key='default-text-57'
                variants={b.getVariants(undefined)}
                className={b.getUniqueClassName()}
                style={undefined}
                text={'SEE MORE'}
                data-d={getKey(rs, '17c99fe8ddb14c88a00330e2')}
              />
            </Typography>
          </Grid>
        </Grid>
        <Grid
          key='grid-43'
          variants={b.getVariants(undefined)}
          item={true}
          container={true}
          data-d={getKey(rs, '17c9015809314c88a003323d')}
        >
          <Hook
            key='mediaScrollHook'
            variants={b.getVariants(undefined)}
            hookModule={MediaScrollHookBaseHookModule}
            arguments={[]}
            data-d={getKey(rs, '17c901642bb14c88a0033243')}
          >
            {((r, v) => (...mediaScrollHookArgs) => {
              const newVariables = {};
            
              let variables = {
                ...v,
                ...newVariables
              };
            
              const rs = report(r, '17c901642bb14c88a0033243', '1791eb63ceefae252001b80a', mediaScrollHookArgs, newVariables);
            
              const renderFn = [
                <Box
                  key='box-20'
                  variants={b.getVariants(undefined)}
                  sx={{
                    ml: {
                    xs: -2,
                    sm: -5,
                    md: 0,
                  },
                    mr: {
                    xs: -2,
                    sm: -5,
                    md: 0,
                  },
                    overflow: 'auto',
                    display: 'flex',
                  }}
                  data-d={getKey(rs, '17c901642bb14c88a0033244')}
                >
                  <Box
                    key='box-14'
                    variants={b.getVariants(undefined)}
                    sx={{
                      width: 100,
                      backgroundColor: 'rgba(224, 224, 224, 0.7)',
                      borderRadius: 1,
                      display: {
                      xs: 'none',
                      md: 'flex',
                    },
                      alignItems: 'center',
                      justifyContent: 'center',
                      'z-index': '100',
                      mb: '5px',
                    }}
                    onClick={b.tryCatch(() => (() => b.propertyBind(mediaScrollHookArgs, ['0','current']).scrollLeft -= 325))}
                    data-d={getKey(rs, '17c901642bb14c88a0033253')}
                  >
                    <Icon
                      key='icon-14'
                      variants={b.getVariants(undefined)}
                      sx={{
                        color: 'grey.800',
                      }}
                      data-d={getKey(rs, '17c901642bb14c88a0033254')}
                    >
                      {'chevron_left'}
                    </Icon>
                  </Box>
                  <Grid
                    key='grid-44'
                    variants={b.getVariants(undefined)}
                    display={'grid'}
                    sx={{
                      ml: {
                      xs: 0,
                      md: -4,
                    },
                      mr: {
                      xs: 0,
                      md: -4,
                    },
                    }}
                    data-d={getKey(rs, '17c901642bb14c88a0033245')}
                  >
                    <Grid
                      key='courseScroll-2'
                      variants={b.getVariants(undefined)}
                      container={false}
                      sx={{
                        display: 'grid',
                        'grid-gap': '20px',
                        'overflow-x': 'scroll',
                        'scroll-snap-type': 'x proximity',
                        'grid-auto-flow': 'column',
                        'grid-auto-columns': undefined,
                        p: {
                        xs: '10px 15px 20px 15px',
                        md: '10px 0px 20px 40px',
                      },
                        '::-webkit-scrollbar': {
                        display: 'none',
                      },
                        '-ms-overflow-style': 'none',
                        'scroll-behavior': 'smooth',
                        'grid-auto-rows': 'auto',
                      }}
                      ref={b.tryCatch(() => (b.propertyBind(mediaScrollHookArgs, ['0'])))}
                      data-d={getKey(rs, '17c901642bb14c88a0033246')}
                    >
                      <CardMediaHomepage
                        key='card-media-homepage-1'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17c901e7ed414c88a00332af')}
                      />
                      <CardMediaHomepage
                        key='card-media-homepage-11'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17c901ed20614c88a00332b9')}
                      />
                      <CardMediaHomepage
                        key='card-media-homepage-10'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17c901ecf0114c88a00332b8')}
                      />
                      <CardMediaHomepage
                        key='card-media-homepage-9'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17c901ecdf214c88a00332b7')}
                      />
                      <CardMediaHomepage
                        key='card-media-homepage-8'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17c901ecb8914c88a00332b6')}
                      />
                      <CardMediaHomepage
                        key='card-media-homepage-7'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17c901ec9f614c88a00332b5')}
                      />
                      <CardMediaHomepage
                        key='card-media-homepage-6'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17c901ec96314c88a00332b4')}
                      />
                      <CardMediaHomepage
                        key='card-media-homepage-5'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17c901ec84914c88a00332b3')}
                      />
                      <CardMediaHomepage
                        key='card-media-homepage-4'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17c901ec76914c88a00332b2')}
                      />
                      <CardMediaHomepage
                        key='card-media-homepage-3'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17c901ec67a14c88a00332b1')}
                      />
                      <CardMediaHomepage
                        key='card-media-homepage-2'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17c901ec52b14c88a00332b0')}
                      />
                      <CardHomepageEndCard
                        key='card-provider-homepage-end-card-3'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17c901642bb14c88a0033247')}
                      />
                    </Grid>
                  </Grid>
                  <Box
                    key='box-15'
                    variants={b.getVariants(undefined)}
                    sx={{
                      width: 100,
                      backgroundColor: 'rgba(224, 224, 224, 0.7)',
                      borderRadius: 1,
                      display: {
                      xs: 'none',
                      md: 'flex',
                    },
                      alignItems: 'center',
                      justifyContent: 'center',
                      'z-index': '100',
                      mb: '5px',
                    }}
                    onClick={b.tryCatch(() => (() => b.propertyBind(mediaScrollHookArgs, ['0','current']).scrollLeft += 325))}
                    data-d={getKey(rs, '17c901642bc14c88a0033256')}
                  >
                    <Icon
                      key='icon-15'
                      variants={b.getVariants(undefined)}
                      sx={{
                        color: 'grey.800',
                      }}
                      fontSize={''}
                      data-d={getKey(rs, '17c901642bc14c88a0033257')}
                    >
                      {'chevron_right'}
                    </Icon>
                  </Box>
                </Box>
              ];
            
              return typeof renderFn === 'function' ? renderFn(...mediaScrollHookArgs) : renderFn;
            })(rs, variables)}
          </Hook>
        </Grid>
      </Grid>
    ]);
  };
  ;
