/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
import React from 'react';
import * as b from '@clutch-creator/bridge';
import Card from '../Card';
import CardActionArea from '../Card Action Area';
import CardMedia from '../Card Media';
import CardContent from '../Card Content';
import Grid from '../Grid';
import Typography from '../Typography';
import Text from '@clutch-marketplace/web-elements/dist/cjs/components/Text';
import Chip from '../Chip';
import CardActions from '../Card Actions';
import Box from '../Box';
import State from '@clutch-marketplace/logic/dist/cjs/components/State';
import Rating from '../Rating';
import Button from '../Button';
import styles from './styles.module.css';

export default (props) => {
    const [report, getKey] = b.useReport(props);
    const { variants } = props;
    const variables = {};
  
    const rs = report(null, '17c8fde8a0714c88a00330ae', 'COMPOSITION', props, variables);
  
    return ([
      <Card
        key='card-11'
        variants={b.getVariants(undefined)}
        sx={{
          width: 300,
          height: 450,
        }}
        raised={true}
        data-d={getKey(rs, '17c8fde8a0714c88a00330af')}
      >
        <CardActionArea
          key='card-action-area-3'
          variants={b.getVariants(undefined)}
          data-d={getKey(rs, '17c8fde8a0714c88a00330bb')}
        >
          <CardMedia
            key='card-media-10'
            variants={b.getVariants(undefined)}
            image={'https://images.squarespace-cdn.com/content/v1/5a734c9af43b55b6cd5466a1/1542989568344-BVJ2RBYWUAMIDUF79HOJ/Inna+Shnayder+%40Inna.Shnayder-8+%283%29.jpg?format=300w'}
            component={'img'}
            sx={{
              maxHeight: 150,
              objectFit: 'cover',
            }}
            data-d={getKey(rs, '17c8fde8a0714c88a00330c5')}
          />
          <CardContent
            key='card-content-11'
            variants={b.getVariants(undefined)}
            sx={{
              height: 254,
            }}
            data-d={getKey(rs, '17c8fde8a0714c88a00330bc')}
          >
            <Grid
              key='grid-27'
              variants={b.getVariants(undefined)}
              container={true}
              direction={'column'}
              alignItems={'flex-start'}
              rowSpacing={1.5}
              data-d={getKey(rs, '17c8fde8a0714c88a00330bd')}
            >
              <Grid
                key='grid-29'
                variants={b.getVariants(undefined)}
                direction={'column'}
                container={true}
                item={true}
                data-d={getKey(rs, '17c8fde8a0714c88a00330c0')}
              >
                <Grid
                  key='grid-18'
                  variants={b.getVariants(undefined)}
                  item={true}
                  data-d={getKey(rs, '17c8fe40e6e14c88a00330e8')}
                >
                  <Typography
                    key='typography-12'
                    variants={b.getVariants(undefined)}
                    sx={{
                      pb: 0.5,
                      fontSize: 18,
                      fontWeight: '400',
                      lineHeight: 1.25,
                    }}
                    data-d={getKey(rs, '17c8fde8a0714c88a00330c1')}
                  >
                    <Text
                      key='default-text-48'
                      variants={b.getVariants(undefined)}
                      className={b.getUniqueClassName()}
                      style={undefined}
                      text={'Flow Workshop'}
                      data-d={getKey(rs, '17c8fde8a0714c88a00330c2')}
                    />
                  </Typography>
                </Grid>
                <Grid
                  key='grid-35'
                  variants={b.getVariants(undefined)}
                  item={true}
                  container={true}
                  justifyContent={'space-between'}
                  data-d={getKey(rs, '17c8fe9188714c88a0033105')}
                >
                  <Grid
                    key='grid-19'
                    variants={b.getVariants(undefined)}
                    item={true}
                    data-d={getKey(rs, '17c8ffccdaa14c88a0033197')}
                  >
                    <Typography
                      key='typography-16'
                      variants={b.getVariants(undefined)}
                      variant={'subtitle2'}
                      sx={{
                        color: 'grey.700',
                        pb: 1,
                      }}
                      data-d={getKey(rs, '17c8fe9188714c88a0033106')}
                    >
                      <Text
                        key='default-text-61'
                        variants={b.getVariants(undefined)}
                        className={b.getUniqueClassName()}
                        style={undefined}
                        text={'Erin Claire Jones'}
                        data-d={getKey(rs, '17c8fe9188714c88a0033107')}
                      />
                    </Typography>
                  </Grid>
                  <Grid
                    key='grid-34'
                    variants={b.getVariants(undefined)}
                    item={true}
                    data-d={getKey(rs, '17c8ffd319414c88a003319f')}
                  >
                    <Typography
                      key='typography-17'
                      variants={b.getVariants(undefined)}
                      variant={'subtitle2'}
                      sx={{
                        pb: 1,
                        fontWeight: 700,
                      }}
                      data-d={getKey(rs, '17c8ffd319414c88a00331a0')}
                    >
                      <Text
                        key='default-text-62'
                        variants={b.getVariants(undefined)}
                        className={b.getUniqueClassName()}
                        style={undefined}
                        text={'$195'}
                        data-d={getKey(rs, '17c8ffd319414c88a00331a1')}
                      />
                    </Typography>
                  </Grid>
                </Grid>
                <Grid
                  key='grid-30'
                  variants={b.getVariants(undefined)}
                  container={true}
                  direction={'row'}
                  spacing={undefined}
                  justifyContent={'space-between'}
                  alignItems={'center'}
                  rowSpacing={1}
                  data-d={getKey(rs, '17c8fe492f714c88a00330f1')}
                >
                  <Grid
                    key='grid-28'
                    variants={b.getVariants(undefined)}
                    item={true}
                    data-d={getKey(rs, '17c8ff4d7e414c88a0033157')}
                  >
                    <Chip
                      key='chip-1'
                      variants={b.getVariants(undefined)}
                      label={'Human Design'}
                      size={'small'}
                      color={undefined}
                      data-d={getKey(rs, '17c8fecc51e14c88a0033111')}
                    />
                  </Grid>
                  <Grid
                    key='grid-37'
                    variants={b.getVariants(undefined)}
                    item={true}
                    data-d={getKey(rs, '17c8ff52adf14c88a0033162')}
                  >
                    <Chip
                      key='chip-4'
                      variants={b.getVariants(undefined)}
                      label={'8 Weeks'}
                      size={'small'}
                      color={undefined}
                      data-d={getKey(rs, '17c8ff2f11614c88a003313e')}
                    />
                  </Grid>
                  <Grid
                    key='grid-36'
                    variants={b.getVariants(undefined)}
                    item={true}
                    data-d={getKey(rs, '17c8ff5287d14c88a0033161')}
                  >
                    <Chip
                      key='chip-3'
                      variants={b.getVariants(undefined)}
                      label={'Virtual'}
                      size={'small'}
                      color={undefined}
                      data-d={getKey(rs, '17c8ff2ea7614c88a003313d')}
                    />
                  </Grid>
                </Grid>
              </Grid>
              <Grid
                key='grid-23'
                variants={b.getVariants(undefined)}
                container={true}
                direction={'column'}
                rowGap={1}
                sx={{
                  height: undefined,
                }}
                item={true}
                data-d={getKey(rs, '17c8fde8a0714c88a00330c7')}
              >
                <Grid
                  key='grid-58'
                  variants={b.getVariants(undefined)}
                  container={true}
                  data-d={getKey(rs, '17c8fde8a0714c88a00330c8')}
                >
                  <Typography
                    key='typography-50'
                    variants={b.getVariants(undefined)}
                    variant={'body2'}
                    data-d={getKey(rs, '17c8fde8a0714c88a00330c9')}
                  >
                    <Text
                      key='default-text-105'
                      variants={b.getVariants(undefined)}
                      className={b.mClassnames([
                        b.getUniqueClassName(),
                        styles['clutchClass12055'],
                      ])}
                      style={undefined}
                      text={'A fun, interactive group workshop that teaches you how to identify how and where you are out of alignment and access the tools you need to find your flow.'}
                      tag={'p'}
                      data-d={getKey(rs, '17c8fde8a0714c88a00330ca')}
                    />
                  </Typography>
                </Grid>
              </Grid>
            </Grid>
          </CardContent>
        </CardActionArea>
        <CardActions
          key='card-actions-10'
          variants={b.getVariants(undefined)}
          data-d={getKey(rs, '17c8fde8a0714c88a00330b0')}
        >
          <Grid
            key='grid-54'
            variants={b.getVariants(undefined)}
            container={true}
            data-d={getKey(rs, '17c8fde8a0714c88a00330b1')}
          >
            <Grid
              key='grid-55'
              variants={b.getVariants(undefined)}
              container={true}
              justifyContent={'space-between'}
              alignItems={'center'}
              data-d={getKey(rs, '17c8fde8a0714c88a00330b2')}
            >
              <Box
                key='box-29'
                variants={b.getVariants(undefined)}
                sx={{
                  display: 'flex',
                  alignItems: 'center',
                }}
                data-d={getKey(rs, '17c8fde8a0714c88a00330b3')}
              >
                <State
                  key='number-state-10'
                  variants={b.getVariants(undefined)}
                  initialValue={4.65}
                  data-d={getKey(rs, '17c8fde8a0714c88a00330b4')}
                >
                  {((r, v) => (...numberstate10Args) => {
                    const newVariables = {};
                  
                    let variables = {
                      ...v,
                      ...newVariables
                    };
                  
                    const rs = report(r, '17c8fde8a0714c88a00330b4', '178bf970a34fae252001bf06', numberstate10Args, newVariables);
                  
                    const renderFn = [
                      <Rating
                        key='rating-10'
                        variants={b.getVariants(undefined)}
                        size={'small'}
                        readOnly={true}
                        value={4.65}
                        precision={0.25}
                        data-d={getKey(rs, '17c8fde8a0714c88a00330b5')}
                      />,
                      <Box
                        key='box-30'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17c8fde8a0714c88a00330b6')}
                      >
                        <Typography
                          key='typography-48'
                          variants={b.getVariants(undefined)}
                          variant={'caption'}
                          sx={{
                            fontSize: '11px',
                            pl: 0.5,
                          }}
                          data-d={getKey(rs, '17c8fde8a0714c88a00330b7')}
                        >
                          <Text
                            key='default-text-102'
                            variants={b.getVariants(undefined)}
                            className={b.getUniqueClassName()}
                            style={undefined}
                            text={b.tryCatch(() => ('(' + b.propertyBind(numberstate10Args, ['0','state']) + ')'))}
                            tag={false}
                            data-d={getKey(rs, '17c8fde8a0714c88a00330b8')}
                          />
                        </Typography>
                      </Box>
                    ];
                  
                    return typeof renderFn === 'function' ? renderFn(...numberstate10Args) : renderFn;
                  })(rs, variables)}
                </State>
              </Box>
              <Button
                key='button-22'
                variants={b.getVariants(undefined)}
                variant={'text'}
                size={'small'}
                data-d={getKey(rs, '17c8fde8a0714c88a00330b9')}
              >
                <Text
                  key='default-text-103'
                  variants={b.getVariants(undefined)}
                  className={b.getUniqueClassName()}
                  style={{
                    textTransform: 'capitalize',
                  }}
                  text={'Learn More'}
                  tag={'span'}
                  data-d={getKey(rs, '17c8fde8a0714c88a00330ba')}
                />
              </Button>
            </Grid>
          </Grid>
        </CardActions>
      </Card>
    ]);
  };
  ;
