/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
import React from 'react';
import * as b from '@clutch-creator/bridge';


export default (props) => {
    const [report, getKey] = b.useReport(props);
    const { variants } = props;
    const variables = {};
  
    const rs = report(null, '17c4856244414c88a0033038', 'COMPOSITION', props, variables);
  
    return ([
      <AppBar
        key='app-bar-3'
        variants={b.getVariants(undefined)}
        data-d={getKey(rs, '17c4d70ab0414c88a0033011')}
      />,
      <AppBar
        key='app-bar-4'
        variants={b.getVariants(undefined)}
        data-d={getKey(rs, '17c4d70ad9414c88a0033012')}
      />
    ]);
  };
  ;
