/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
import React from 'react';
import * as b from '@clutch-creator/bridge';
import Button from '../../../components/Button';
import Text from '@clutch-marketplace/web-elements/dist/cjs/components/Text';

export default (props) => {
    const [report, getKey] = b.useReport(props);
    const { variants } = props;
    const variables = {};
  
    const rs = report(null, '17c3e59cff014c88a0033026', 'COMPOSITION', props, variables);
  
    return ([
      <Button
        key='button'
        variants={b.getVariants(undefined)}
        variant={'contained'}
        data-d={getKey(rs, '17c3e59f94614c88a0033029')}
      >
        <Text
          key='default-text-2'
          variants={b.getVariants(undefined)}
          className={b.getUniqueClassName()}
          style={undefined}
          text={'Lorem Ipsum'}
          tag={'span'}
          data-d={getKey(rs, '17c3e5d404514c88a003302e')}
        />
      </Button>
    ]);
  };
  ;
