/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
import React from 'react';
import * as b from '@clutch-creator/bridge';
import HelmetLink from '@clutch-marketplace/helmet/dist/cjs/components/HelmetLink';

export default (props) => {
    const [report, getKey] = b.useReport(props);
    const { variants } = props;
    const variables = {};
  
    const rs = report(null, '17c3e4f20bf14c88a0033021', 'COMPOSITION', props, variables);
  
    return ([
      <HelmetLink
        key='mui-icons'
        variants={b.getVariants(undefined)}
        rel={'stylesheet'}
        href={'https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap'}
        data-d={getKey(rs, '17c3e492bc714c88a0033018')}
      />
    ]);
  };
  ;
