/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
import React from 'react';
import * as b from '@clutch-creator/bridge';
import Grid from '../../../components/Grid';
import State from '@clutch-marketplace/logic/dist/cjs/components/State';
import Element from '@clutch-marketplace/element/dist/cjs/components/Element';
import Button from '../../../components/Button';
import Text from '@clutch-marketplace/web-elements/dist/cjs/components/Text';
import Buttonfilterhomepage1BaseEndIcon from './logic/button-filter-homepage-1/base-endicon.js';
import Menu from '../../../components/Menu';
import MenuItem from '../../../components/MenuItem';

export default (props) => {
    const [report, getKey] = b.useReport(props);
    const { variants } = props;
    const variables = {};
  
    const rs = report(null, '17c4d717d7714c88a0033013', 'COMPOSITION', props, variables);
  
    return ([
      <Grid
        key='grid-61'
        variants={b.getVariants(undefined)}
        sx={{
          order: {
          xs: 1,
        },
        }}
        xs={4}
        md={3}
        data-d={getKey(rs, '17c959427f314c88a0033000')}
      >
        <State
          key='state-filter-homepage-1'
          variants={b.getVariants(undefined)}
          initialValue={undefined}
          data-d={getKey(rs, '17c959427f314c88a0033001')}
        >
          {((r, v) => (...statefilterhomepage1Args) => {
            const newVariables = {};
          
            let variables = {
              ...v,
              ...newVariables
            };
          
            const rs = report(r, '17c959427f314c88a0033001', '178bf970a34fae252001bf06', statefilterhomepage1Args, newVariables);
          
            const renderFn = [
              <Element
                key='div-filter-homepage-1'
                variants={b.getVariants(undefined)}
                tag={'div'}
                data-d={getKey(rs, '17c959427f314c88a0033002')}
              >
                <Button
                  key='button-filter-homepage-1'
                  variants={b.getVariants(undefined)}
                  variant={'contained'}
                  onClick={undefined}
                  endIcon={(Buttonfilterhomepage1BaseEndIcon())}
                  data-d={getKey(rs, '17c959427f314c88a003300c')}
                >
                  <Text
                    key='default-text-74'
                    variants={b.getVariants(undefined)}
                    className={b.getUniqueClassName()}
                    style={undefined}
                    text={'Filter'}
                    tag={'span'}
                    data-d={getKey(rs, '17c959427f314c88a003300d')}
                  />
                </Button>
                <Menu
                  key='menu-filter-homepage-1'
                  variants={b.getVariants(undefined)}
                  open={undefined}
                  autoFocus={undefined}
                  classes={b.getUniqueClassName()}
                  disableAutoFocusItem={undefined}
                  MenuListProps={undefined}
                  onClose={undefined}
                  PopoverClasses={undefined}
                  transitionDuration={undefined}
                  TransitionProps={undefined}
                  variant={undefined}
                  anchorEl={undefined}
                  getContentAnchorEl={'null'}
                  anchorOrigin={{
                    vertical: 'bottom',
                    horizontal: 'left',
                  }}
                  transformOrigin={{
                    horizontal: 'left',
                  }}
                  data-d={getKey(rs, '17c959427f314c88a0033003')}
                >
                  <MenuItem
                    key='menu-item-10'
                    variants={b.getVariants(undefined)}
                    autoFocus={undefined}
                    classes={b.getUniqueClassName()}
                    component={undefined}
                    dense={undefined}
                    disableGutters={undefined}
                    divider={undefined}
                    focusVisibleClassName={undefined}
                    sx={undefined}
                    data-d={getKey(rs, '17c959427f314c88a0033004')}
                  >
                    <Text
                      key='default-text-65'
                      variants={b.getVariants(undefined)}
                      className={b.getUniqueClassName()}
                      style={undefined}
                      text={'Highest Rating'}
                      tag={'span'}
                      data-d={getKey(rs, '17c959427f314c88a0033005')}
                    />
                  </MenuItem>
                  <MenuItem
                    key='menu-item-16'
                    variants={b.getVariants(undefined)}
                    autoFocus={undefined}
                    classes={b.getUniqueClassName()}
                    component={undefined}
                    dense={undefined}
                    disableGutters={undefined}
                    divider={undefined}
                    focusVisibleClassName={undefined}
                    sx={undefined}
                    data-d={getKey(rs, '17c959427f314c88a003300a')}
                  >
                    <Text
                      key='default-text-73'
                      variants={b.getVariants(undefined)}
                      className={b.getUniqueClassName()}
                      style={undefined}
                      text={'Lowest Rating'}
                      tag={'span'}
                      data-d={getKey(rs, '17c959427f314c88a003300b')}
                    />
                  </MenuItem>
                  <MenuItem
                    key='menu-item-15'
                    variants={b.getVariants(undefined)}
                    autoFocus={undefined}
                    classes={b.getUniqueClassName()}
                    component={undefined}
                    dense={undefined}
                    disableGutters={undefined}
                    divider={undefined}
                    focusVisibleClassName={undefined}
                    sx={undefined}
                    data-d={getKey(rs, '17c959427f314c88a0033008')}
                  >
                    <Text
                      key='default-text-72'
                      variants={b.getVariants(undefined)}
                      className={b.getUniqueClassName()}
                      style={undefined}
                      text={'Most Reviews'}
                      tag={'span'}
                      data-d={getKey(rs, '17c959427f314c88a0033009')}
                    />
                  </MenuItem>
                  <MenuItem
                    key='menu-item-14'
                    variants={b.getVariants(undefined)}
                    autoFocus={undefined}
                    classes={b.getUniqueClassName()}
                    component={undefined}
                    dense={undefined}
                    disableGutters={undefined}
                    divider={undefined}
                    focusVisibleClassName={undefined}
                    sx={undefined}
                    data-d={getKey(rs, '17c959427f314c88a0033006')}
                  >
                    <Text
                      key='default-text-66'
                      variants={b.getVariants(undefined)}
                      className={b.getUniqueClassName()}
                      style={undefined}
                      text={'Least Reviews'}
                      tag={'span'}
                      data-d={getKey(rs, '17c959427f314c88a0033007')}
                    />
                  </MenuItem>
                </Menu>
              </Element>
            ];
          
            return typeof renderFn === 'function' ? renderFn(...statefilterhomepage1Args) : renderFn;
          })(rs, variables)}
        </State>
      </Grid>
    ]);
  };
  ;
