/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
import React from 'react';
import * as b from '@clutch-creator/bridge';
import Grid from '../../../components/Grid';

export default (props) => {
    const [report, getKey] = b.useReport(props);
    const { variants } = props;
    const variables = {};
  
    const rs = report(null, '17c3e86f89114c88a0033015', 'COMPOSITION', props, variables);
  
    return ([
      <Grid
        key='grid'
        variants={b.getVariants(undefined)}
        columns={undefined}
        classes={b.getUniqueClassName()}
        columnSpacing={undefined}
        container={undefined}
        direction={undefined}
        item={undefined}
        xs={undefined}
        sm={undefined}
        md={undefined}
        lg={undefined}
        xl={undefined}
        rowSpacing={undefined}
        spacing={undefined}
        wrap={undefined}
        zeroMinWidth={undefined}
        data-d={getKey(rs, '17c3e8a700814c88a0033000')}
      >
        {null}
      </Grid>
    ]);
  };
  ;
