/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
import React from 'react';
import * as b from '@clutch-creator/bridge';
import MUIApp from '../../../components/MUI App';

export default (props) => {
    const [report, getKey] = b.useReport(props);
    const { variants } = props;
    const variables = {};
  
    const rs = report(null, '17c3e436c9214c88a0033007', 'COMPOSITION', props, variables);
  
    return ([
      <MUIApp
        key='mui-app-2'
        variants={b.getVariants(undefined)}
        data-d={getKey(rs, '17c4d6b7a7014c88a0033000')}
      />
    ]);
  };
  ;
