/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
import React from 'react';
import * as b from '@clutch-creator/bridge';
import AppleMusicPodcastEmbed from '../../../components/Apple Music Podcast Embed';

export default (props) => {
    const [report, getKey] = b.useReport(props);
    const { variants } = props;
    const variables = {};
  
    const rs = report(null, '17c9582fb9714c88a0033023', 'COMPOSITION', props, variables);
  
    return ([
      <AppleMusicPodcastEmbed
        key='apple-music-podcast-embed-1'
        variants={b.getVariants(undefined)}
        link={'https://podcasts.apple.com/us/podcast/dayluna-human-design-podcast/id1470324538'}
        width={'100%'}
        data-d={getKey(rs, '17c95830dff14c88a0033025')}
      />
    ]);
  };
  ;
