/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
import React from 'react';
import * as b from '@clutch-creator/bridge';
import Grid from '../Grid';
import Box from '../Box';
import Icon from '../Icon';
import Text from '@clutch-marketplace/web-elements/dist/cjs/components/Text';

export default (props) => {
    const [report, getKey] = b.useReport(props);
    const { variants } = props;
    const variables = {};
  
    const rs = report(null, '17c8144002f14c88a0033074', 'COMPOSITION', props, variables);
  
    return ([
      <Grid
        key='grid-22'
        variants={b.getVariants(undefined)}
        xs={6}
        container={true}
        data-d={getKey(rs, '17c8116dc8714c88a0033284')}
      >
        <Box
          key='box-12'
          variants={b.getVariants(undefined)}
          sx={undefined}
          data-d={getKey(rs, '17c811e9dd714c88a0033004')}
        >
          <Grid
            key='grid-17'
            variants={b.getVariants(undefined)}
            columnSpacing={0.35}
            container={true}
            columns={undefined}
            data-d={getKey(rs, '17c811e9dd714c88a0033005')}
          >
            <Icon
              key='icon-8'
              variants={b.getVariants(undefined)}
              sx={{
                color: 'grey.500',
                ml: 0.5,
              }}
              data-d={getKey(rs, '17c811e9dd814c88a0033006')}
            >
              <Text
                key='default-text-52'
                variants={b.getVariants(undefined)}
                className={b.getUniqueClassName()}
                style={undefined}
                text={'school'}
                tag={'span'}
                data-d={getKey(rs, '17c811e9dd814c88a0033007')}
              />
            </Icon>
            <Icon
              key='icon-12'
              variants={b.getVariants(undefined)}
              sx={{
                color: 'grey.500',
                ml: 0.5,
              }}
              data-d={getKey(rs, '17c811e9dd914c88a003300e')}
            >
              <Text
                key='default-text-56'
                variants={b.getVariants(undefined)}
                className={b.getUniqueClassName()}
                style={undefined}
                text={'group'}
                tag={undefined}
                data-d={getKey(rs, '17c811e9dda14c88a003300f')}
              />
            </Icon>
            <Icon
              key='icon-9'
              variants={b.getVariants(undefined)}
              sx={{
                color: 'grey.500',
                ml: 0.5,
              }}
              data-d={getKey(rs, '17c811e9dd914c88a0033008')}
            >
              <Text
                key='default-text-53'
                variants={b.getVariants(undefined)}
                className={b.getUniqueClassName()}
                style={undefined}
                text={'subscriptions'}
                tag={'span'}
                data-d={getKey(rs, '17c811e9dd914c88a0033009')}
              />
            </Icon>
            <Icon
              key='icon-10'
              variants={b.getVariants(undefined)}
              sx={{
                color: 'grey.500',
                ml: 0.5,
              }}
              data-d={getKey(rs, '17c811e9dd914c88a003300a')}
            >
              <Text
                key='default-text-54'
                variants={b.getVariants(undefined)}
                className={b.getUniqueClassName()}
                style={undefined}
                text={'group'}
                tag={'span'}
                data-d={getKey(rs, '17c811e9dd914c88a003300b')}
              />
            </Icon>
            <Icon
              key='icon-11'
              variants={b.getVariants(undefined)}
              sx={{
                color: 'grey.500',
                ml: 0.5,
              }}
              data-d={getKey(rs, '17c811e9dd914c88a003300c')}
            >
              <Text
                key='default-text-55'
                variants={b.getVariants(undefined)}
                className={b.getUniqueClassName()}
                style={undefined}
                text={'event'}
                tag={'span'}
                data-d={getKey(rs, '17c811e9dd914c88a003300d')}
              />
            </Icon>
          </Grid>
        </Box>
      </Grid>
    ]);
  };
  ;
