/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
import React from 'react';
import * as b from '@clutch-creator/bridge';
import Card from '@clutch-marketplace/react-bootstrap/dist/cjs/components/Card';
import CardImg from '@clutch-marketplace/react-bootstrap/dist/cjs/components/CardImg';
import CardBody from '@clutch-marketplace/react-bootstrap/dist/cjs/components/CardBody';
import CardTitle from '@clutch-marketplace/react-bootstrap/dist/cjs/components/CardTitle';
import Text from '@clutch-marketplace/web-elements/dist/cjs/components/Text';
import CardSubtitle from '@clutch-marketplace/react-bootstrap/dist/cjs/components/CardSubtitle';
import Icon from '@clutch-marketplace/heroicons/dist/cjs/components/Icon';
import CardText from '@clutch-marketplace/react-bootstrap/dist/cjs/components/CardText';
import CardLink from '@clutch-marketplace/react-bootstrap/dist/cjs/components/CardLink';
import CardFooter from '@clutch-marketplace/react-bootstrap/dist/cjs/components/CardFooter';
import Badge from '@clutch-marketplace/react-bootstrap/dist/cjs/components/Badge';
import styles from './styles.module.css';

export default (props) => {
    const [report, getKey] = b.useReport(props);
    const { variants } = props;
    const variables = {};
  
    const rs = report(null, '61576d1465507b003260dabf', 'COMPOSITION', props, variables);
  
    return ([
      <Card
        key='filter-provider-card'
        variants={b.getVariants(undefined)}
        as={undefined}
        bg={undefined}
        body={undefined}
        border={undefined}
        text={undefined}
        className={b.mClassnames([
          b.getUniqueClassName(),
          styles['clutchClass11956'],
        ])}
        style={undefined}
        data-d={getKey(rs, '61576d1465507b003260dab3')}
      >
        <CardImg
          key='default-CardImg-27'
          variants={b.getVariants(undefined)}
          as={undefined}
          variant={undefined}
          src={'https://mzlzqjzvhavxetaoqwde.supabase.in/storage/v1/object/sign/profile-images/Erin Claire Jones.jpg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcm9maWxlLWltYWdlcy9FcmluIENsYWlyZSBKb25lcy5qcGciLCJpYXQiOjE2MzI1MjMyNzksImV4cCI6MTk0Nzg4MzI3OX0.RxuZpRF8NZj8MPpFP5ngP6VGlInLonXuCmNaJh95P70'}
          className={b.mClassnames([
            b.getUniqueClassName(),
            styles['clutchClass11940'],
          ])}
          style={undefined}
          data-d={getKey(rs, '61576d1465507b003260dab4')}
        />
        <CardBody
          key='default-CardBody-40'
          variants={b.getVariants(undefined)}
          as={undefined}
          className={b.getUniqueClassName()}
          style={undefined}
          data-d={getKey(rs, '61576d1465507b003260dab2')}
        >
          <CardTitle
            key='default-CardTitle-29'
            variants={b.getVariants(undefined)}
            className={b.getUniqueClassName()}
            style={undefined}
            data-d={getKey(rs, '61576d1465507b003260dab6')}
          >
            <Text
              key='default-text-501'
              variants={b.getVariants(undefined)}
              className={b.getUniqueClassName()}
              style={undefined}
              text={'Erin Claire Jones'}
              tag={'span'}
              data-d={getKey(rs, '61576d1465507b003260daba')}
            />
          </CardTitle>
          <CardSubtitle
            key='default-CardSubtitle-2'
            variants={b.getVariants(undefined)}
            className={b.getUniqueClassName()}
            style={undefined}
            data-d={getKey(rs, '61576d1465507b003260daf8')}
          >
            <Icon
              key='Heroicon-solid-6'
              variants={b.getVariants(undefined)}
              name={'star'}
              solid={true}
              color={'grey'}
              size={24}
              data-d={getKey(rs, '61576d1465507b003260dafd')}
            />
            <Icon
              key='Heroicon-solid-10'
              variants={b.getVariants(undefined)}
              name={'star'}
              solid={true}
              color={'grey'}
              size={24}
              data-d={getKey(rs, '61576d1465507b003260dafa')}
            />
            <Icon
              key='Heroicon-solid-9'
              variants={b.getVariants(undefined)}
              name={'star'}
              solid={true}
              color={'grey'}
              size={24}
              data-d={getKey(rs, '61576d1465507b003260dafc')}
            />
            <Icon
              key='Heroicon-solid-8'
              variants={b.getVariants(undefined)}
              name={'star'}
              solid={true}
              color={'grey'}
              size={24}
              data-d={getKey(rs, '61576d1465507b003260daf9')}
            />
            <Icon
              key='Heroicon-solid-7'
              variants={b.getVariants(undefined)}
              name={'star'}
              solid={true}
              color={'grey'}
              size={24}
              data-d={getKey(rs, '61576d1465507b003260dafb')}
            />
          </CardSubtitle>
          <CardText
            key='default-CardText-29'
            variants={b.getVariants(undefined)}
            className={b.getUniqueClassName()}
            style={undefined}
            data-d={getKey(rs, '61576d1465507b003260dab8')}
          >
            <Text
              key='default-text-510'
              variants={b.getVariants(undefined)}
              className={b.getUniqueClassName()}
              style={undefined}
              text={'As a Human Design Guide & Leadership Coach, I offer you a blueprint to how you operate so you can perform at the top of your personal and professional game.'}
              tag={'span'}
              data-d={getKey(rs, '61576d1465507b003260dab9')}
            />
          </CardText>
          <CardLink
            key='default-CardLink-8'
            variants={b.getVariants(undefined)}
            href={undefined}
            className={b.getUniqueClassName()}
            style={undefined}
            data-d={getKey(rs, '61576d1465507b003260dab5')}
          >
            <Text
              key='default-text-517'
              variants={b.getVariants(undefined)}
              className={b.getUniqueClassName()}
              style={undefined}
              text={undefined}
              tag={'span'}
              data-d={getKey(rs, '61576d1465507b003260dab7')}
            />
          </CardLink>
        </CardBody>
        <CardFooter
          key='default-CardFooter-2'
          variants={b.getVariants(undefined)}
          className={b.mClassnames([
            b.getUniqueClassName(),
            styles['clutchClass11955'],
          ])}
          style={undefined}
          data-d={getKey(rs, '61576d1465507b003260daf1')}
        >
          <Badge
            key='default-Badge-5'
            variants={b.getVariants(undefined)}
            as={undefined}
            pill={false}
            className={b.mClassnames([
              b.getUniqueClassName(),
              'mr-1',
            ])}
            style={undefined}
            variant={'info'}
            data-d={getKey(rs, '61576d1465507b003260daf2')}
          >
            <Text
              key='default-text-8'
              variants={b.getVariants(undefined)}
              className={b.getUniqueClassName()}
              style={undefined}
              text={'Human Design'}
              tag={'span'}
              data-d={getKey(rs, '61576d1465507b003260daf4')}
            />
          </Badge>
          <Badge
            key='default-Badge-7'
            variants={b.getVariants(undefined)}
            as={undefined}
            pill={false}
            className={b.mClassnames([
              b.getUniqueClassName(),
              'mr-1',
            ])}
            style={undefined}
            variant={'danger'}
            data-d={getKey(rs, '61576d1465507b003260daf3')}
          >
            <Text
              key='default-text-10'
              variants={b.getVariants(undefined)}
              className={b.getUniqueClassName()}
              style={undefined}
              text={'Courses'}
              tag={'span'}
              data-d={getKey(rs, '61576d1465507b003260daf7')}
            />
          </Badge>
          <Badge
            key='default-Badge-6'
            variants={b.getVariants(undefined)}
            as={undefined}
            pill={false}
            className={b.getUniqueClassName()}
            style={undefined}
            variant={'success'}
            data-d={getKey(rs, '61576d1465507b003260daf5')}
          >
            <Text
              key='default-text-9'
              variants={b.getVariants(undefined)}
              className={b.getUniqueClassName()}
              style={undefined}
              text={'Media'}
              tag={'span'}
              data-d={getKey(rs, '61576d1465507b003260daf6')}
            />
          </Badge>
        </CardFooter>
      </Card>
    ]);
  };
  ;
