/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
import React from 'react';
import * as b from '@clutch-creator/bridge';
import Container from '@clutch-marketplace/react-bootstrap/dist/cjs/components/Container';
import Row from '@clutch-marketplace/react-bootstrap/dist/cjs/components/Row';
import Col from '@clutch-marketplace/react-bootstrap/dist/cjs/components/Col';
import Text from '@clutch-marketplace/web-elements/dist/cjs/components/Text';
import Button from '@clutch-marketplace/react-bootstrap/dist/cjs/components/Button';
import Image from '@clutch-marketplace/react-bootstrap/dist/cjs/components/Image';
import styles from './styles.module.css';

export default (props) => {
    const [report, getKey] = b.useReport(props);
    const { variants } = props;
    const variables = {};
  
    const rs = report(null, '61576d1465507b003260da8f', 'COMPOSITION', props, variables);
  
    return ([
      <Container
        key='container-signed-out-masthead'
        variants={b.getVariants(undefined)}
        fluid={true}
        className={b.mClassnames([
          b.getUniqueClassName(),
          styles['clutchClass11931'],
          'bg-light',
        ])}
        style={undefined}
        data-d={getKey(rs, '61576d1465507b003260da85')}
      >
        <Row
          key='row-signed-out-masthead'
          variants={b.getVariants(undefined)}
          noGutters={undefined}
          className={b.mClassnames([
            b.getUniqueClassName(),
            styles['clutchClass11932'],
          ])}
          style={undefined}
          data-d={getKey(rs, '61576d1465507b003260da86')}
        >
          <Col
            key='text-content'
            variants={b.getVariants(undefined)}
            className={b.mClassnames([
              b.getUniqueClassName(),
              styles['clutchClass11933'],
            ])}
            style={undefined}
            data-d={getKey(rs, '61576d1465507b003260da88')}
          >
            <Text
              key='title-signed-out-masthead'
              variants={b.getVariants(undefined)}
              className={b.mClassnames([
                b.getUniqueClassName(),
                styles['clutchClass11934'],
                'text-secondary',
              ])}
              style={undefined}
              text={'Discover a community from around the world'}
              tag={'h1'}
              data-d={getKey(rs, '61576d1465507b003260da89')}
            />
            <Text
              key='text-signed-out-masthead'
              variants={b.getVariants(undefined)}
              className={b.mClassnames([
                b.getUniqueClassName(),
                styles['clutchClass11935'],
              ])}
              style={undefined}
              text={'Luminate is the leading destination to find & showcase providers, services and resources to assist you on your personal journey'}
              tag={'p'}
              data-d={getKey(rs, '61576d1465507b003260da8a')}
            />
            <Button
              key='button-signed-out-masthead'
              variants={b.getVariants(undefined)}
              active={undefined}
              as={undefined}
              block={undefined}
              disabled={undefined}
              href={undefined}
              size={undefined}
              type={'button'}
              className={b.getUniqueClassName()}
              style={undefined}
              onClick={undefined}
              variant={'primary'}
              data-d={getKey(rs, '61576d1465507b003260da8b')}
            >
              <Text
                key='button-text-signed-out-masthead'
                variants={b.getVariants(undefined)}
                className={b.getUniqueClassName()}
                style={undefined}
                text={'Sign Up'}
                tag={'span'}
                data-d={getKey(rs, '61576d1465507b003260da8c')}
              />
            </Button>
          </Col>
          <Col
            key='shot-content'
            variants={b.getVariants(undefined)}
            className={b.mClassnames([
              b.getUniqueClassName(),
              styles['clutchClass11938'],
            ])}
            style={undefined}
            data-d={getKey(rs, '61576d1465507b003260da8d')}
          >
            <Image
              key='shot-content-image'
              variants={b.getVariants(undefined)}
              src={'https://images.prismic.io/luminate/143d9333-8d56-450b-9064-218a6f1e30ff_Earth500px.png'}
              fluid={undefined}
              rounded={undefined}
              roundedCircle={undefined}
              thumbnail={undefined}
              alt={undefined}
              height={undefined}
              width={undefined}
              className={b.mClassnames([
                b.getUniqueClassName(),
                styles['clutchClass11939'],
              ])}
              style={undefined}
              data-d={getKey(rs, '61576d1465507b003260da8e')}
            />
          </Col>
        </Row>
      </Container>
    ]);
  };
  ;
