/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
import React from 'react';
import * as b from '@clutch-creator/bridge';
import Card from '../Card';
import CardActionArea from '../Card Action Area';
import CardContent from '../Card Content';
import Grid from '../Grid';
import Avatar from '../Avatar';
import Typography from '../Typography';
import Text from '@clutch-marketplace/web-elements/dist/cjs/components/Text';
import CardMedia from '../Card Media';
import CardActions from '../Card Actions';
import Box from '../Box';
import State from '@clutch-marketplace/logic/dist/cjs/components/State';
import Rating from '../Rating';
import Button from '../Button';
import styles from './styles.module.css';

export default (props) => {
    const [report, getKey] = b.useReport(props);
    const { variants } = props;
    const variables = {};
  
    const rs = report(null, '17c8677035014c88a003331d', 'COMPOSITION', props, variables);
  
    return ([
      <Card
        key='card-9'
        variants={b.getVariants(undefined)}
        sx={{
          width: 300,
          height: 450,
        }}
        raised={true}
        data-d={getKey(rs, '17c8170acc814c88a0033304')}
      >
        <CardActionArea
          key='card-action-area-1'
          variants={b.getVariants(undefined)}
          data-d={getKey(rs, '17c86980aa314c88a003336c')}
        >
          <CardContent
            key='card-content-10'
            variants={b.getVariants(undefined)}
            sx={undefined}
            data-d={getKey(rs, '17c86747c5a14c88a0033300')}
          >
            <Grid
              key='grid-24'
              variants={b.getVariants(undefined)}
              container={true}
              direction={'row'}
              alignItems={'center'}
              data-d={getKey(rs, '17c86747c5a14c88a0033302')}
            >
              <Grid
                key='grid-25'
                variants={b.getVariants(undefined)}
                sx={{
                  mr: 2,
                  width: 56,
                  height: 56,
                  borderRadius: '50%',
                }}
                data-d={getKey(rs, '17c86747c5a14c88a0033303')}
              >
                <Avatar
                  key='avatar-2'
                  variants={b.getVariants(undefined)}
                  src={'https://mzlzqjzvhavxetaoqwde.supabase.in/storage/v1/object/sign/profile-images/Erin Claire Jones.jpg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcm9maWxlLWltYWdlcy9FcmluIENsYWlyZSBKb25lcy5qcGciLCJpYXQiOjE2MzI1MjMyNzksImV4cCI6MTk0Nzg4MzI3OX0.RxuZpRF8NZj8MPpFP5ngP6VGlInLonXuCmNaJh95P70'}
                  sx={{
                    width: '56px',
                    height: '56px',
                  }}
                  variant={'circular'}
                  imgProps={{
                    width: 56,
                    height: 56,
                    sx: {
                    borderRadius: '50%',
                  },
                  }}
                  data-d={getKey(rs, '17c86747c5a14c88a0033304')}
                />
              </Grid>
              <Grid
                key='grid-26'
                variants={b.getVariants(undefined)}
                direction={'column'}
                data-d={getKey(rs, '17c86747c5a14c88a0033305')}
              >
                <Typography
                  key='typography-9'
                  variants={b.getVariants(undefined)}
                  sx={{
                    pb: 0,
                    fontSize: 18,
                    fontWeight: '400',
                  }}
                  data-d={getKey(rs, '17c86747c5a14c88a0033306')}
                >
                  <Text
                    key='default-text-4'
                    variants={b.getVariants(undefined)}
                    className={b.getUniqueClassName()}
                    style={undefined}
                    text={'Erin Claire Jones'}
                    data-d={getKey(rs, '17c86747c5a14c88a0033307')}
                  />
                </Typography>
                <Typography
                  key='typography-11'
                  variants={b.getVariants(undefined)}
                  variant={'caption'}
                  sx={{
                    color: 'grey.700',
                  }}
                  data-d={getKey(rs, '17c86747c5a14c88a0033308')}
                >
                  <Text
                    key='default-text-44'
                    variants={b.getVariants(undefined)}
                    className={b.getUniqueClassName()}
                    style={undefined}
                    text={'Human Design Coach'}
                    data-d={getKey(rs, '17c86747c5a14c88a0033309')}
                  />
                </Typography>
              </Grid>
            </Grid>
          </CardContent>
          <CardMedia
            key='card-media-9'
            variants={b.getVariants(undefined)}
            image={'https://www.lavendaire.com/wp-content/uploads/2020/05/Erin-Claire-Jones-1024x682.png'}
            component={'img'}
            sx={{
              maxHeight: 150,
              objectFit: 'cover',
            }}
            data-d={getKey(rs, '17c8170acc814c88a0033307')}
          />
          <CardContent
            key='card-content-9'
            variants={b.getVariants(undefined)}
            sx={{
              height: 166,
            }}
            data-d={getKey(rs, '17c8170acc814c88a0033308')}
          >
            <Grid
              key='grid-20'
              variants={b.getVariants(undefined)}
              container={true}
              direction={'column'}
              rowGap={1}
              sx={{
                height: undefined,
              }}
              data-d={getKey(rs, '17c8668d49d14c88a00332b1')}
            >
              <Grid
                key='grid-51'
                variants={b.getVariants(undefined)}
                container={true}
                data-d={getKey(rs, '17c8170acc914c88a0033310')}
              >
                <Typography
                  key='typography-46'
                  variants={b.getVariants(undefined)}
                  variant={'body2'}
                  data-d={getKey(rs, '17c8170acc914c88a0033311')}
                >
                  <Text
                    key='default-text-99'
                    variants={b.getVariants(undefined)}
                    className={b.mClassnames([
                      b.getUniqueClassName(),
                      styles['clutchClass12042'],
                    ])}
                    style={undefined}
                    text={'As a Human Design Guide & Leadership Coach, I offer you a blueprint to how you operate so you can perform at the top of your personal and professional game. '}
                    tag={'span'}
                    data-d={getKey(rs, '17c8170acc914c88a0033312')}
                  />
                </Typography>
              </Grid>
              <Grid
                key='grid-50'
                variants={b.getVariants(undefined)}
                container={true}
                data-d={getKey(rs, '17c8170acc814c88a0033309')}
              >
                <Typography
                  key='typography-43'
                  variants={b.getVariants(undefined)}
                  variant={'caption'}
                  sx={{
                    mr: 0.5,
                  }}
                  data-d={getKey(rs, '17c8170acc814c88a003330a')}
                >
                  <Text
                    key='default-text-96'
                    variants={b.getVariants(undefined)}
                    className={b.getUniqueClassName()}
                    style={undefined}
                    text={'#Human Design'}
                    tag={'span'}
                    data-d={getKey(rs, '17c8170acc914c88a003330b')}
                  />
                </Typography>
                <Typography
                  key='typography-45'
                  variants={b.getVariants(undefined)}
                  variant={'caption'}
                  sx={{
                    mr: 0.5,
                  }}
                  data-d={getKey(rs, '17c8170acc914c88a003330e')}
                >
                  <Text
                    key='default-text-98'
                    variants={b.getVariants(undefined)}
                    className={b.getUniqueClassName()}
                    style={undefined}
                    text={'#Business'}
                    tag={'span'}
                    data-d={getKey(rs, '17c8170acc914c88a003330f')}
                  />
                </Typography>
                <Typography
                  key='typography-44'
                  variants={b.getVariants(undefined)}
                  variant={'caption'}
                  sx={{
                    mr: 0.5,
                  }}
                  data-d={getKey(rs, '17c8170acc914c88a003330c')}
                >
                  <Text
                    key='default-text-97'
                    variants={b.getVariants(undefined)}
                    className={b.getUniqueClassName()}
                    style={undefined}
                    text={'#Courses'}
                    tag={'span'}
                    data-d={getKey(rs, '17c8170acc914c88a003330d')}
                  />
                </Typography>
              </Grid>
            </Grid>
          </CardContent>
        </CardActionArea>
        <CardActions
          key='card-actions-9'
          variants={b.getVariants(undefined)}
          data-d={getKey(rs, '17c8170acc914c88a0033313')}
        >
          <Grid
            key='grid-52'
            variants={b.getVariants(undefined)}
            container={true}
            data-d={getKey(rs, '17c8170acc914c88a0033314')}
          >
            <Grid
              key='grid-53'
              variants={b.getVariants(undefined)}
              container={true}
              justifyContent={'space-between'}
              alignItems={'center'}
              data-d={getKey(rs, '17c8170acc914c88a0033315')}
            >
              <Box
                key='box-27'
                variants={b.getVariants(undefined)}
                sx={{
                  display: 'flex',
                  alignItems: 'center',
                }}
                data-d={getKey(rs, '17c8170acc914c88a0033316')}
              >
                <State
                  key='number-state-9'
                  variants={b.getVariants(undefined)}
                  initialValue={3.75}
                  data-d={getKey(rs, '17c8170acc914c88a0033317')}
                >
                  {((r, v) => (...numberstate9Args) => {
                    const newVariables = {};
                  
                    let variables = {
                      ...v,
                      ...newVariables
                    };
                  
                    const rs = report(r, '17c8170acc914c88a0033317', '178bf970a34fae252001bf06', numberstate9Args, newVariables);
                  
                    const renderFn = [
                      <Rating
                        key='rating-9'
                        variants={b.getVariants(undefined)}
                        size={'small'}
                        readOnly={true}
                        value={3.75}
                        precision={0.25}
                        data-d={getKey(rs, '17c8170acc914c88a0033318')}
                      />,
                      <Box
                        key='box-28'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17c8170acc914c88a0033319')}
                      >
                        <Typography
                          key='typography-47'
                          variants={b.getVariants(undefined)}
                          variant={'caption'}
                          sx={{
                            fontSize: '11px',
                            pl: 0.5,
                          }}
                          data-d={getKey(rs, '17c8170acc914c88a003331a')}
                        >
                          <Text
                            key='default-text-100'
                            variants={b.getVariants(undefined)}
                            className={b.getUniqueClassName()}
                            style={undefined}
                            text={b.tryCatch(() => ('(' + b.propertyBind(numberstate9Args, ['0','state']) + ')'))}
                            tag={false}
                            data-d={getKey(rs, '17c8170acc914c88a003331b')}
                          />
                        </Typography>
                      </Box>
                    ];
                  
                    return typeof renderFn === 'function' ? renderFn(...numberstate9Args) : renderFn;
                  })(rs, variables)}
                </State>
              </Box>
              <Button
                key='button-21'
                variants={b.getVariants(undefined)}
                variant={'text'}
                size={'small'}
                data-d={getKey(rs, '17c8170acc914c88a003331c')}
              >
                <Text
                  key='default-text-101'
                  variants={b.getVariants(undefined)}
                  className={b.getUniqueClassName()}
                  style={{
                    textTransform: 'capitalize',
                  }}
                  text={'Learn More'}
                  tag={'span'}
                  data-d={getKey(rs, '17c8170acc914c88a003331d')}
                />
              </Button>
            </Grid>
          </Grid>
        </CardActions>
      </Card>
    ]);
  };
  ;
