/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
import React from 'react';
import * as b from '@clutch-creator/bridge';
import HelmetMeta from '@clutch-marketplace/helmet/dist/cjs/components/HelmetMeta';
import HelmetLink from '@clutch-marketplace/helmet/dist/cjs/components/HelmetLink';
import AppBar from '../../../components/App Bar';
import Box from '../../../components/Box';
import Toolbar from '../../../components/Toolbar';
import Typography from '../../../components/Typography';
import Text from '@clutch-marketplace/web-elements/dist/cjs/components/Text';
import ButtonGroup from '../../../components/ButtonGroup';
import Button from '../../../components/Button';
import IconButton from '../../../components/IconButton';
import Icon from '../../../components/Icon';
import MobileMenu from '../../../components/MobileMenu';
import LoggedOutMasthead from '../../../components/Logged Out Masthead';
import Grid from '../../../components/Grid';
import State from '@clutch-marketplace/logic/dist/cjs/components/State';
import Element from '@clutch-marketplace/element/dist/cjs/components/Element';
import Buttonfilterhomepage2BaseEndIcon from './logic/button-filter-homepage-2/base-endicon.js';
import Menu from '../../../components/Menu';
import MenuItem from '../../../components/MenuItem';
import FormControl from '../../../components/Form Control';
import OutlinedInput from '../../../components/OutlinedInput';
import Outlinedinput2BaseEndAdornment from './logic/outlined-input-2/base-endadornment.js';
import CardProviderHomepage from '../../../components/Card - Provider Homepage';
import CardHomepageEndCard from '../../../components/Card - Homepage End Card';
import Buttonfilterhomepage3BaseEndIcon from './logic/button-filter-homepage-3/base-endicon-1.js';
import Outlinedinput3BaseEndAdornment from './logic/outlined-input-3/base-endadornment-1.js';

export default (props) => {
    const [report, getKey] = b.useReport(props);
    const { variants } = props;
    const variables = {};
  
    const rs = report(null, '17ca525ab8214c88a003313e', 'COMPOSITION', props, variables);
  
    return ([
      <HelmetMeta
        key='meta-viewport-3'
        variants={b.getVariants(undefined)}
        content={'initial-scale=1, width=device-width'}
        name={'viewport'}
        data-d={getKey(rs, '17ca526951214c88a0033141')}
      />,
      <HelmetLink
        key='font-roboto-1'
        variants={b.getVariants(undefined)}
        rel={'stylesheet'}
        href={'https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap'}
        data-d={getKey(rs, '17ca526a66d14c88a0033142')}
      />,
      <HelmetLink
        key='font-icons-2'
        variants={b.getVariants(undefined)}
        rel={'stylesheet'}
        href={'https://fonts.googleapis.com/icon?family=Material+Icons'}
        data-d={getKey(rs, '17ca526b4db14c88a0033143')}
      />,
      <AppBar
        key='app-bar-6'
        variants={b.getVariants(undefined)}
        classes={b.getUniqueClassName()}
        color={undefined}
        enableColorOnDark={undefined}
        position={'static'}
        sx={undefined}
        data-d={getKey(rs, '17ca526cd3c14c88a0033144')}
      >
        <Box
          key='box-7'
          variants={b.getVariants(undefined)}
          sx={{
            flexGrow: '1',
          }}
          data-d={getKey(rs, '17ca526cd3c14c88a0033145')}
        >
          <Toolbar
            key='toolbar-2'
            variants={b.getVariants(undefined)}
            classes={b.getUniqueClassName()}
            disableGutters={undefined}
            sx={undefined}
            variant={undefined}
            data-d={getKey(rs, '17ca526cd3c14c88a0033146')}
          >
            <Typography
              key='typo-brand-1'
              variants={b.getVariants(undefined)}
              align={undefined}
              classes={b.getUniqueClassName()}
              gutterBottom={undefined}
              noWrap={true}
              paragraph={undefined}
              sx={undefined}
              variant={'h6'}
              component={'div'}
              data-d={getKey(rs, '17ca526cd3c14c88a0033147')}
            >
              <Text
                key='text-brand-1'
                variants={b.getVariants(undefined)}
                className={b.getUniqueClassName()}
                style={undefined}
                text={'Luminate'}
                tag={'span'}
                data-d={getKey(rs, '17ca526cd3c14c88a0033148')}
              />
            </Typography>
            <Box
              key='box-18'
              variants={b.getVariants(undefined)}
              sx={{
                display: {
                xs: 'none',
                md: 'flex',
              },
              }}
              data-d={getKey(rs, '17ca526cd3c14c88a0033149')}
            >
              <ButtonGroup
                key='button-group-2'
                variants={b.getVariants(undefined)}
                classes={b.getUniqueClassName()}
                color={undefined}
                component={undefined}
                disabled={undefined}
                disableElevation={undefined}
                disableFocusRipple={undefined}
                disableRipple={undefined}
                fullWidth={undefined}
                orientation={undefined}
                size={undefined}
                sx={{
                  'margin-left': '25px',
                }}
                variant={undefined}
                data-d={getKey(rs, '17ca526cd3c14c88a003314a')}
              >
                <Button
                  key='button-14'
                  variants={b.getVariants(undefined)}
                  classes={b.getUniqueClassName()}
                  color={'inherit'}
                  variant={'text'}
                  data-d={getKey(rs, '17ca526cd3c14c88a003314b')}
                >
                  <Text
                    key='default-text-17'
                    variants={b.getVariants(undefined)}
                    className={b.getUniqueClassName()}
                    style={undefined}
                    text={'Providers'}
                    tag={'span'}
                    data-d={getKey(rs, '17ca526cd3c14c88a003314c')}
                  />
                </Button>
                <Button
                  key='button-15'
                  variants={b.getVariants(undefined)}
                  classes={b.getUniqueClassName()}
                  color={'inherit'}
                  variant={'text'}
                  data-d={getKey(rs, '17ca526cd3c14c88a003314d')}
                >
                  <Text
                    key='default-text-18'
                    variants={b.getVariants(undefined)}
                    className={b.getUniqueClassName()}
                    style={undefined}
                    text={'Courses'}
                    tag={'span'}
                    data-d={getKey(rs, '17ca526cd3c14c88a003314e')}
                  />
                </Button>
                <Button
                  key='button-17'
                  variants={b.getVariants(undefined)}
                  classes={b.getUniqueClassName()}
                  color={'inherit'}
                  variant={'text'}
                  data-d={getKey(rs, '17ca526cd3c14c88a003314f')}
                >
                  <Text
                    key='default-text-42'
                    variants={b.getVariants(undefined)}
                    className={b.getUniqueClassName()}
                    style={undefined}
                    text={'Media'}
                    tag={'span'}
                    data-d={getKey(rs, '17ca526cd3c14c88a0033150')}
                  />
                </Button>
                <Button
                  key='button-18'
                  variants={b.getVariants(undefined)}
                  classes={b.getUniqueClassName()}
                  color={'inherit'}
                  variant={'text'}
                  data-d={getKey(rs, '17ca526cd3c14c88a0033151')}
                >
                  <Text
                    key='default-text-43'
                    variants={b.getVariants(undefined)}
                    className={b.getUniqueClassName()}
                    style={undefined}
                    text={'Resources'}
                    tag={'span'}
                    data-d={getKey(rs, '17ca526cd3c14c88a0033152')}
                  />
                </Button>
                <Button
                  key='button-19'
                  variants={b.getVariants(undefined)}
                  classes={b.getUniqueClassName()}
                  color={'inherit'}
                  variant={'text'}
                  data-d={getKey(rs, '17ca526cd3c14c88a0033153')}
                >
                  <Text
                    key='default-text-79'
                    variants={b.getVariants(undefined)}
                    className={b.getUniqueClassName()}
                    style={undefined}
                    text={'Events'}
                    tag={'span'}
                    data-d={getKey(rs, '17ca526cd3c14c88a0033154')}
                  />
                </Button>
              </ButtonGroup>
            </Box>
            <Box
              key='box-37'
              variants={b.getVariants(undefined)}
              sx={{
                flexGrow: '1',
              }}
              data-d={getKey(rs, '17ca526cd3c14c88a003315a')}
            >
              {null}
            </Box>
            <Box
              key='box-21'
              variants={b.getVariants(undefined)}
              sx={{
                display: {
                xs: 'none',
                md: 'flex',
              },
              }}
              data-d={getKey(rs, '17ca526cd3c14c88a0033155')}
            >
              <IconButton
                key='icon-button-4'
                variants={b.getVariants(undefined)}
                data-d={getKey(rs, '17ca526cd3c14c88a0033156')}
              >
                <Icon
                  key='icon-menu-5'
                  variants={b.getVariants(undefined)}
                  sx={{
                    color: '#ffffff',
                  }}
                  data-d={getKey(rs, '17ca526cd3c14c88a0033157')}
                >
                  {'account_circle'}
                </Icon>
              </IconButton>
              <IconButton
                key='icon-button-5'
                variants={b.getVariants(undefined)}
                data-d={getKey(rs, '17ca526cd3c14c88a0033158')}
              >
                <Icon
                  key='icon-menu-6'
                  variants={b.getVariants(undefined)}
                  sx={{
                    color: '#ffffff',
                  }}
                  data-d={getKey(rs, '17ca526cd3c14c88a0033159')}
                >
                  {'settings'}
                </Icon>
              </IconButton>
            </Box>
            <MobileMenu
              key='mobile-menu-1'
              variants={b.getVariants(undefined)}
              data-d={getKey(rs, '17ca526cd3c14c88a003315b')}
            />
          </Toolbar>
        </Box>
      </AppBar>,
      <LoggedOutMasthead
        key='logged-out-masthead-2'
        variants={b.getVariants(undefined)}
        data-d={getKey(rs, '17ca526e55514c88a003315c')}
      />,
      <Grid
        key='content-homepage'
        variants={b.getVariants(undefined)}
        container={true}
        direction={'column'}
        rowSpacing={2}
        sx={{
          mt: 2,
          pl: {
          xs: 2,
          sm: 5,
          md: 10,
        },
          pr: {
          xs: 2,
          sm: 5,
          md: 10,
        },
        }}
        data-d={getKey(rs, '17ca527f49f14c88a003315e')}
      >
        <Grid
          key='grid-homepage-filter-1'
          variants={b.getVariants(undefined)}
          container={true}
          sx={{
            pl: {
            xs: 2,
            sm: 5,
            lg: 10,
          },
            pr: {
            xs: 2,
            sm: 5,
            lg: 10,
          },
          }}
          alignItems={'center'}
          item={true}
          data-d={getKey(rs, '17ca52918f314c88a0033166')}
        >
          <Grid
            key='grid-68'
            variants={b.getVariants(undefined)}
            sx={{
              order: {
              xs: 1,
            },
            }}
            xs={4}
            md={3}
            data-d={getKey(rs, '17ca52918f314c88a0033167')}
          >
            <State
              key='state-filter-homepage-2'
              variants={b.getVariants(undefined)}
              initialValue={undefined}
              data-d={getKey(rs, '17ca52918f314c88a0033168')}
            >
              {((r, v) => (...statefilterhomepage2Args) => {
                const newVariables = {};
              
                let variables = {
                  ...v,
                  ...newVariables
                };
              
                const rs = report(r, '17ca52918f314c88a0033168', '178bf970a34fae252001bf06', statefilterhomepage2Args, newVariables);
              
                const renderFn = [
                  <Element
                    key='div-filter-homepage-2'
                    variants={b.getVariants(undefined)}
                    tag={'div'}
                    data-d={getKey(rs, '17ca52918f314c88a0033169')}
                  >
                    <Button
                      key='button-filter-homepage-2'
                      variants={b.getVariants(undefined)}
                      variant={'contained'}
                      onClick={b.tryCatch(() => ((event) => b.propertyBind(statefilterhomepage2Args, ['0','setState'])(event.currentTarget)))}
                      endIcon={(Buttonfilterhomepage2BaseEndIcon())}
                      data-d={getKey(rs, '17ca52918f414c88a0033173')}
                    >
                      <Text
                        key='default-text-84'
                        variants={b.getVariants(undefined)}
                        className={b.getUniqueClassName()}
                        style={undefined}
                        text={'Filter'}
                        tag={'span'}
                        data-d={getKey(rs, '17ca52918f414c88a0033174')}
                      />
                    </Button>
                    <Menu
                      key='menu-filter-homepage-2'
                      variants={b.getVariants(undefined)}
                      open={b.tryCatch(() => (Boolean(b.propertyBind(statefilterhomepage2Args, ['0','state']))))}
                      autoFocus={undefined}
                      classes={b.getUniqueClassName()}
                      disableAutoFocusItem={undefined}
                      MenuListProps={undefined}
                      onClose={b.tryCatch(() => (() => b.propertyBind(statefilterhomepage2Args, ['0','setState'])('')))}
                      PopoverClasses={undefined}
                      transitionDuration={undefined}
                      TransitionProps={undefined}
                      variant={undefined}
                      anchorEl={b.tryCatch(() => (b.propertyBind(statefilterhomepage2Args, ['0','state'])))}
                      getContentAnchorEl={'null'}
                      anchorOrigin={{
                        vertical: 'bottom',
                        horizontal: 'left',
                      }}
                      transformOrigin={{
                        horizontal: 'left',
                      }}
                      data-d={getKey(rs, '17ca52918f314c88a003316a')}
                    >
                      <MenuItem
                        key='menu-item-17'
                        variants={b.getVariants(undefined)}
                        autoFocus={undefined}
                        classes={b.getUniqueClassName()}
                        component={undefined}
                        dense={undefined}
                        disableGutters={undefined}
                        divider={undefined}
                        focusVisibleClassName={undefined}
                        sx={undefined}
                        data-d={getKey(rs, '17ca52918f314c88a003316b')}
                      >
                        <Text
                          key='default-text-80'
                          variants={b.getVariants(undefined)}
                          className={b.getUniqueClassName()}
                          style={undefined}
                          text={'Highest Rating'}
                          tag={'span'}
                          data-d={getKey(rs, '17ca52918f414c88a003316c')}
                        />
                      </MenuItem>
                      <MenuItem
                        key='menu-item-20'
                        variants={b.getVariants(undefined)}
                        autoFocus={undefined}
                        classes={b.getUniqueClassName()}
                        component={undefined}
                        dense={undefined}
                        disableGutters={undefined}
                        divider={undefined}
                        focusVisibleClassName={undefined}
                        sx={undefined}
                        data-d={getKey(rs, '17ca52918f414c88a0033171')}
                      >
                        <Text
                          key='default-text-83'
                          variants={b.getVariants(undefined)}
                          className={b.getUniqueClassName()}
                          style={undefined}
                          text={'Lowest Rating'}
                          tag={'span'}
                          data-d={getKey(rs, '17ca52918f414c88a0033172')}
                        />
                      </MenuItem>
                      <MenuItem
                        key='menu-item-19'
                        variants={b.getVariants(undefined)}
                        autoFocus={undefined}
                        classes={b.getUniqueClassName()}
                        component={undefined}
                        dense={undefined}
                        disableGutters={undefined}
                        divider={undefined}
                        focusVisibleClassName={undefined}
                        sx={undefined}
                        data-d={getKey(rs, '17ca52918f414c88a003316f')}
                      >
                        <Text
                          key='default-text-82'
                          variants={b.getVariants(undefined)}
                          className={b.getUniqueClassName()}
                          style={undefined}
                          text={'Most Reviews'}
                          tag={'span'}
                          data-d={getKey(rs, '17ca52918f414c88a0033170')}
                        />
                      </MenuItem>
                      <MenuItem
                        key='menu-item-18'
                        variants={b.getVariants(undefined)}
                        autoFocus={undefined}
                        classes={b.getUniqueClassName()}
                        component={undefined}
                        dense={undefined}
                        disableGutters={undefined}
                        divider={undefined}
                        focusVisibleClassName={undefined}
                        sx={undefined}
                        data-d={getKey(rs, '17ca52918f414c88a003316d')}
                      >
                        <Text
                          key='default-text-81'
                          variants={b.getVariants(undefined)}
                          className={b.getUniqueClassName()}
                          style={undefined}
                          text={'Least Reviews'}
                          tag={'span'}
                          data-d={getKey(rs, '17ca52918f414c88a003316e')}
                        />
                      </MenuItem>
                    </Menu>
                  </Element>
                ];
              
                return typeof renderFn === 'function' ? renderFn(...statefilterhomepage2Args) : renderFn;
              })(rs, variables)}
            </State>
          </Grid>
          <Grid
            key='grid-122'
            variants={b.getVariants(undefined)}
            xs={12}
            md={6}
            sx={{
              order: {
              xs: 3,
              md: '2',
            },
              mt: {
              xs: 2,
              md: '0',
            },
            }}
            wrap={'wrap'}
            container={true}
            justifyContent={'center'}
            data-d={getKey(rs, '17ca52918f414c88a0033176')}
          >
            <Button
              key='button-20'
              variants={b.getVariants(undefined)}
              classes={b.getUniqueClassName()}
              color={'primary'}
              variant={'text'}
              sx={{
                textTransform: 'capitalize',
              }}
              data-d={getKey(rs, '17ca52918f414c88a0033177')}
            >
              <Text
                key='default-text-85'
                variants={b.getVariants(undefined)}
                className={b.getUniqueClassName()}
                style={undefined}
                text={'All'}
                tag={'span'}
                data-d={getKey(rs, '17ca52918f414c88a0033178')}
              />
            </Button>
            <Button
              key='button-25'
              variants={b.getVariants(undefined)}
              classes={b.getUniqueClassName()}
              color={'primary'}
              variant={'text'}
              sx={{
                'text-transform': 'capitalize',
              }}
              data-d={getKey(rs, '17ca52918f414c88a0033179')}
            >
              <Text
                key='default-text-86'
                variants={b.getVariants(undefined)}
                className={b.getUniqueClassName()}
                style={undefined}
                text={'Astrology'}
                tag={'span'}
                data-d={getKey(rs, '17ca52918f414c88a003317a')}
              />
            </Button>
            <Button
              key='button-26'
              variants={b.getVariants(undefined)}
              classes={b.getUniqueClassName()}
              color={'primary'}
              variant={'text'}
              sx={{
                'text-transform': 'capitalize',
              }}
              data-d={getKey(rs, '17ca52918f414c88a003317b')}
            >
              <Text
                key='default-text-87'
                variants={b.getVariants(undefined)}
                className={b.getUniqueClassName()}
                style={undefined}
                text={'Human Design'}
                tag={'span'}
                data-d={getKey(rs, '17ca52918f414c88a003317c')}
              />
            </Button>
            <Button
              key='button-32'
              variants={b.getVariants(undefined)}
              classes={b.getUniqueClassName()}
              color={'primary'}
              variant={'text'}
              sx={{
                'text-transform': 'capitalize',
              }}
              data-d={getKey(rs, '17ca52918f414c88a003317d')}
            >
              <Text
                key='default-text-88'
                variants={b.getVariants(undefined)}
                className={b.getUniqueClassName()}
                style={undefined}
                text={'Metaphysical'}
                tag={'span'}
                data-d={getKey(rs, '17ca52918f414c88a003317e')}
              />
            </Button>
            <Button
              key='button-33'
              variants={b.getVariants(undefined)}
              classes={b.getUniqueClassName()}
              color={'primary'}
              variant={'text'}
              sx={{
                'text-transform': 'capitalize',
              }}
              data-d={getKey(rs, '17ca52918f414c88a003317f')}
            >
              <Text
                key='default-text-89'
                variants={b.getVariants(undefined)}
                className={b.getUniqueClassName()}
                style={undefined}
                text={'Psychology'}
                tag={'span'}
                data-d={getKey(rs, '17ca52918f414c88a0033180')}
              />
            </Button>
            <Button
              key='button-34'
              variants={b.getVariants(undefined)}
              classes={b.getUniqueClassName()}
              color={'primary'}
              variant={'text'}
              sx={{
                'text-transform': 'capitalize',
              }}
              data-d={getKey(rs, '17ca52918f414c88a0033181')}
            >
              <Text
                key='default-text-90'
                variants={b.getVariants(undefined)}
                className={b.getUniqueClassName()}
                style={undefined}
                text={'Cards'}
                tag={'span'}
                data-d={getKey(rs, '17ca52918f414c88a0033182')}
              />
            </Button>
          </Grid>
          <Grid
            key='grid-123'
            variants={b.getVariants(undefined)}
            xs={8}
            md={3}
            justifyContents={'flex-end'}
            sx={{
              order: {
              xs: 2,
              md: 3,
            },
            }}
            data-d={getKey(rs, '17ca52918f414c88a0033183')}
          >
            <Box
              key='box-38'
              variants={b.getVariants(undefined)}
              data-d={getKey(rs, '17ca52918f414c88a0033184')}
            >
              <Grid
                key='grid-126'
                variants={b.getVariants(undefined)}
                container={true}
                justifyContent={'flex-end'}
                data-d={getKey(rs, '17ca52918f414c88a0033185')}
              >
                <Grid
                  key='grid-127'
                  variants={b.getVariants(undefined)}
                  item={true}
                  data-d={getKey(rs, '17ca52918f414c88a0033186')}
                >
                  <FormControl
                    key='form-control-2'
                    variants={b.getVariants(undefined)}
                    variant={'outlined'}
                    size={'small'}
                    color={'primary'}
                    data-d={getKey(rs, '17ca52918f414c88a0033187')}
                  >
                    <OutlinedInput
                      key='outlined-input-2'
                      variants={b.getVariants(undefined)}
                      placeholder={'Search...'}
                      startAdornment={undefined}
                      type={'search'}
                      sx={{
                        '& MuiOutlinedInput-notchedOutline': {
                        borderColor: 'primary.main',
                      },
                        backgroundColor: 'rgba(66, 165, 245, 0.05)',
                        borderColor: 'primary.main',
                      }}
                      endAdornment={(Outlinedinput2BaseEndAdornment())}
                      data-d={getKey(rs, '17ca52918f414c88a0033188')}
                    />
                  </FormControl>
                </Grid>
              </Grid>
            </Box>
          </Grid>
        </Grid>
        <Grid
          key='grid-providers-cards-3'
          variants={b.getVariants(undefined)}
          container={true}
          xs={12}
          item={true}
          data-d={getKey(rs, '17ca52b3b6814c88a003318a')}
        >
          <Grid
            key='grid-128'
            variants={b.getVariants(undefined)}
            item={true}
            container={true}
            justifyContent={'space-between'}
            alignItems={'center'}
            xs={12}
            data-d={getKey(rs, '17ca52b3b6814c88a003318b')}
          >
            <Grid
              key='grid-129'
              variants={b.getVariants(undefined)}
              item={true}
              data-d={getKey(rs, '17ca52b3b6814c88a003318c')}
            >
              <Typography
                key='typography-30'
                variants={b.getVariants(undefined)}
                gutterBottom={false}
                variant={'h5'}
                sx={{
                  fontWeight: '500',
                  color: 'primary.main',
                  fontSize: '1.75rem',
                  lineHeight: {
                  xs: '1.5',
                  md: '1.75',
                },
                }}
                data-d={getKey(rs, '17ca52b3b6814c88a003318d')}
              >
                <Text
                  key='default-text-91'
                  variants={b.getVariants(undefined)}
                  className={b.getUniqueClassName()}
                  style={undefined}
                  text={'Providers'}
                  tag={'span'}
                  data-d={getKey(rs, '17ca52b3b6814c88a003318e')}
                />
              </Typography>
            </Grid>
            <Grid
              key='grid-130'
              variants={b.getVariants(undefined)}
              item={true}
              data-d={getKey(rs, '17ca52b3b6814c88a003318f')}
            >
              <Typography
                key='typography-31'
                variants={b.getVariants(undefined)}
                gutterBottom={false}
                variant={'subtitle2'}
                sx={{
                  fontWeight: '500',
                  ':hover': {
                  color: 'primary.dark',
                },
                  color: 'primary.main',
                }}
                data-d={getKey(rs, '17ca52b3b6814c88a0033190')}
              >
                <Text
                  key='default-text-92'
                  variants={b.getVariants(undefined)}
                  className={b.getUniqueClassName()}
                  style={undefined}
                  text={'SEE MORE'}
                  data-d={getKey(rs, '17ca52b3b6814c88a0033191')}
                />
              </Typography>
            </Grid>
          </Grid>
          <Grid
            key='grid-131'
            variants={b.getVariants(undefined)}
            item={true}
            container={true}
            xs={12}
            data-d={getKey(rs, '17ca52b3b6814c88a0033192')}
          >
            <Grid
              key='grid-132'
              variants={b.getVariants(undefined)}
              sx={{
                overflow: 'auto',
                display: 'flex',
                ml: {
                xs: -2,
                sm: -5,
                md: 0,
              },
                mr: {
                xs: -2,
                sm: -5,
                md: 0,
              },
              }}
              data-d={getKey(rs, '17ca52b3b6814c88a0033193')}
            >
              <Grid
                key='grid-133'
                variants={b.getVariants(undefined)}
                display={'grid'}
                sx={{
                  ml: {
                  xs: 0,
                  md: -4,
                },
                  mr: {
                  xs: 0,
                  md: -4,
                },
                }}
                item={true}
                container={true}
                data-d={getKey(rs, '17ca52b3b6814c88a0033194')}
              >
                <Grid
                  key='providerScroll-2'
                  variants={b.getVariants(undefined)}
                  container={false}
                  sx={{
                    display: 'grid',
                    'grid-gap': '20px',
                    'overflow-x': 'scroll',
                    'scroll-snap-type': 'x proximity',
                    'grid-auto-flow': 'column',
                    'grid-auto-columns': undefined,
                    p: {
                    xs: '10px 15px 20px 15px',
                    md: '10px 0px 20px 40px',
                  },
                    '::-webkit-scrollbar': {
                    display: 'none',
                  },
                    '-ms-overflow-style': 'none',
                    'scroll-behavior': 'smooth',
                    'grid-auto-rows': 'auto',
                  }}
                  data-d={getKey(rs, '17ca52b3b6814c88a0033195')}
                >
                  <CardProviderHomepage
                    key='card-provider-homepage-23'
                    variants={b.getVariants(undefined)}
                    data-d={getKey(rs, '17ca52b3b6814c88a0033196')}
                  />
                  <CardProviderHomepage
                    key='card-provider-homepage-33'
                    variants={b.getVariants(undefined)}
                    data-d={getKey(rs, '17ca52b3b6814c88a00331a0')}
                  />
                  <CardProviderHomepage
                    key='card-provider-homepage-32'
                    variants={b.getVariants(undefined)}
                    data-d={getKey(rs, '17ca52b3b6814c88a003319f')}
                  />
                  <CardProviderHomepage
                    key='card-provider-homepage-31'
                    variants={b.getVariants(undefined)}
                    data-d={getKey(rs, '17ca52b3b6814c88a003319e')}
                  />
                  <CardProviderHomepage
                    key='card-provider-homepage-30'
                    variants={b.getVariants(undefined)}
                    data-d={getKey(rs, '17ca52b3b6814c88a003319d')}
                  />
                  <CardProviderHomepage
                    key='card-provider-homepage-29'
                    variants={b.getVariants(undefined)}
                    data-d={getKey(rs, '17ca52b3b6814c88a003319c')}
                  />
                  <CardProviderHomepage
                    key='card-provider-homepage-28'
                    variants={b.getVariants(undefined)}
                    data-d={getKey(rs, '17ca52b3b6814c88a003319b')}
                  />
                  <CardProviderHomepage
                    key='card-provider-homepage-27'
                    variants={b.getVariants(undefined)}
                    data-d={getKey(rs, '17ca52b3b6814c88a003319a')}
                  />
                  <CardProviderHomepage
                    key='card-provider-homepage-26'
                    variants={b.getVariants(undefined)}
                    data-d={getKey(rs, '17ca52b3b6814c88a0033199')}
                  />
                  <CardProviderHomepage
                    key='card-provider-homepage-25'
                    variants={b.getVariants(undefined)}
                    data-d={getKey(rs, '17ca52b3b6814c88a0033198')}
                  />
                  <CardProviderHomepage
                    key='card-provider-homepage-24'
                    variants={b.getVariants(undefined)}
                    data-d={getKey(rs, '17ca52b3b6814c88a0033197')}
                  />
                  <CardHomepageEndCard
                    key='card-provider-homepage-end-card-6'
                    variants={b.getVariants(undefined)}
                    data-d={getKey(rs, '17ca52b3b6814c88a00331a1')}
                  />
                </Grid>
              </Grid>
            </Grid>
          </Grid>
        </Grid>
        <Grid
          key='grid-homepage-filter-2'
          variants={b.getVariants(undefined)}
          container={true}
          sx={{
            pl: {
            xs: 2,
            sm: 5,
            lg: 10,
          },
            pr: {
            xs: 2,
            sm: 5,
            lg: 10,
          },
          }}
          alignItems={'center'}
          item={true}
          data-d={getKey(rs, '17ca53c3c3914c88a0033207')}
        >
          <Grid
            key='grid-134'
            variants={b.getVariants(undefined)}
            sx={{
              order: {
              xs: 1,
            },
            }}
            xs={4}
            md={3}
            data-d={getKey(rs, '17ca53c3c3914c88a0033208')}
          >
            <State
              key='state-filter-homepage-3'
              variants={b.getVariants(undefined)}
              initialValue={undefined}
              data-d={getKey(rs, '17ca53c3c3914c88a0033209')}
            >
              {((r, v) => (...statefilterhomepage3Args) => {
                const newVariables = {};
              
                let variables = {
                  ...v,
                  ...newVariables
                };
              
                const rs = report(r, '17ca53c3c3914c88a0033209', '178bf970a34fae252001bf06', statefilterhomepage3Args, newVariables);
              
                const renderFn = [
                  <Element
                    key='div-filter-homepage-3'
                    variants={b.getVariants(undefined)}
                    tag={'div'}
                    data-d={getKey(rs, '17ca53c3c3914c88a003320a')}
                  >
                    <Button
                      key='button-filter-homepage-3'
                      variants={b.getVariants(undefined)}
                      variant={'contained'}
                      onClick={b.tryCatch(() => ((event) => b.propertyBind(statefilterhomepage3Args, ['0','setState'])(event.currentTarget)))}
                      endIcon={(Buttonfilterhomepage3BaseEndIcon())}
                      data-d={getKey(rs, '17ca53c3c3914c88a0033214')}
                    >
                      <Text
                        key='default-text-113'
                        variants={b.getVariants(undefined)}
                        className={b.getUniqueClassName()}
                        style={undefined}
                        text={'Filter'}
                        tag={'span'}
                        data-d={getKey(rs, '17ca53c3c3914c88a0033215')}
                      />
                    </Button>
                    <Menu
                      key='menu-filter-homepage-3'
                      variants={b.getVariants(undefined)}
                      open={b.tryCatch(() => (Boolean(b.propertyBind(statefilterhomepage3Args, ['0','state']))))}
                      autoFocus={undefined}
                      classes={b.getUniqueClassName()}
                      disableAutoFocusItem={undefined}
                      MenuListProps={undefined}
                      onClose={b.tryCatch(() => (() => b.propertyBind(statefilterhomepage3Args, ['0','setState'])('')))}
                      PopoverClasses={undefined}
                      transitionDuration={undefined}
                      TransitionProps={undefined}
                      variant={undefined}
                      anchorEl={b.tryCatch(() => (b.propertyBind(statefilterhomepage3Args, ['0','state'])))}
                      getContentAnchorEl={'null'}
                      anchorOrigin={{
                        vertical: 'bottom',
                        horizontal: 'left',
                      }}
                      transformOrigin={{
                        horizontal: 'left',
                      }}
                      data-d={getKey(rs, '17ca53c3c3914c88a003320b')}
                    >
                      <MenuItem
                        key='menu-item-21'
                        variants={b.getVariants(undefined)}
                        autoFocus={undefined}
                        classes={b.getUniqueClassName()}
                        component={undefined}
                        dense={undefined}
                        disableGutters={undefined}
                        divider={undefined}
                        focusVisibleClassName={undefined}
                        sx={undefined}
                        data-d={getKey(rs, '17ca53c3c3914c88a003320c')}
                      >
                        <Text
                          key='default-text-93'
                          variants={b.getVariants(undefined)}
                          className={b.getUniqueClassName()}
                          style={undefined}
                          text={'Highest Rating'}
                          tag={'span'}
                          data-d={getKey(rs, '17ca53c3c3914c88a003320d')}
                        />
                      </MenuItem>
                      <MenuItem
                        key='menu-item-24'
                        variants={b.getVariants(undefined)}
                        autoFocus={undefined}
                        classes={b.getUniqueClassName()}
                        component={undefined}
                        dense={undefined}
                        disableGutters={undefined}
                        divider={undefined}
                        focusVisibleClassName={undefined}
                        sx={undefined}
                        data-d={getKey(rs, '17ca53c3c3914c88a0033212')}
                      >
                        <Text
                          key='default-text-112'
                          variants={b.getVariants(undefined)}
                          className={b.getUniqueClassName()}
                          style={undefined}
                          text={'Lowest Rating'}
                          tag={'span'}
                          data-d={getKey(rs, '17ca53c3c3914c88a0033213')}
                        />
                      </MenuItem>
                      <MenuItem
                        key='menu-item-23'
                        variants={b.getVariants(undefined)}
                        autoFocus={undefined}
                        classes={b.getUniqueClassName()}
                        component={undefined}
                        dense={undefined}
                        disableGutters={undefined}
                        divider={undefined}
                        focusVisibleClassName={undefined}
                        sx={undefined}
                        data-d={getKey(rs, '17ca53c3c3914c88a0033210')}
                      >
                        <Text
                          key='default-text-95'
                          variants={b.getVariants(undefined)}
                          className={b.getUniqueClassName()}
                          style={undefined}
                          text={'Most Reviews'}
                          tag={'span'}
                          data-d={getKey(rs, '17ca53c3c3914c88a0033211')}
                        />
                      </MenuItem>
                      <MenuItem
                        key='menu-item-22'
                        variants={b.getVariants(undefined)}
                        autoFocus={undefined}
                        classes={b.getUniqueClassName()}
                        component={undefined}
                        dense={undefined}
                        disableGutters={undefined}
                        divider={undefined}
                        focusVisibleClassName={undefined}
                        sx={undefined}
                        data-d={getKey(rs, '17ca53c3c3914c88a003320e')}
                      >
                        <Text
                          key='default-text-94'
                          variants={b.getVariants(undefined)}
                          className={b.getUniqueClassName()}
                          style={undefined}
                          text={'Least Reviews'}
                          tag={'span'}
                          data-d={getKey(rs, '17ca53c3c3914c88a003320f')}
                        />
                      </MenuItem>
                    </Menu>
                  </Element>
                ];
              
                return typeof renderFn === 'function' ? renderFn(...statefilterhomepage3Args) : renderFn;
              })(rs, variables)}
            </State>
          </Grid>
          <Grid
            key='grid-135'
            variants={b.getVariants(undefined)}
            xs={12}
            md={6}
            sx={{
              order: {
              xs: 3,
              md: '2',
            },
              mt: {
              xs: 2,
              md: '0',
            },
            }}
            wrap={'wrap'}
            container={true}
            justifyContent={'center'}
            data-d={getKey(rs, '17ca53c3c3a14c88a0033217')}
          >
            <Button
              key='button-35'
              variants={b.getVariants(undefined)}
              classes={b.getUniqueClassName()}
              color={'primary'}
              variant={'text'}
              sx={{
                textTransform: 'capitalize',
              }}
              data-d={getKey(rs, '17ca53c3c3a14c88a0033218')}
            >
              <Text
                key='default-text-114'
                variants={b.getVariants(undefined)}
                className={b.getUniqueClassName()}
                style={undefined}
                text={'All'}
                tag={'span'}
                data-d={getKey(rs, '17ca53c3c3a14c88a0033219')}
              />
            </Button>
            <Button
              key='button-36'
              variants={b.getVariants(undefined)}
              classes={b.getUniqueClassName()}
              color={'primary'}
              variant={'text'}
              sx={{
                'text-transform': 'capitalize',
              }}
              data-d={getKey(rs, '17ca53c3c3a14c88a003321a')}
            >
              <Text
                key='default-text-115'
                variants={b.getVariants(undefined)}
                className={b.getUniqueClassName()}
                style={undefined}
                text={'Astrology'}
                tag={'span'}
                data-d={getKey(rs, '17ca53c3c3a14c88a003321b')}
              />
            </Button>
            <Button
              key='button-37'
              variants={b.getVariants(undefined)}
              classes={b.getUniqueClassName()}
              color={'primary'}
              variant={'text'}
              sx={{
                'text-transform': 'capitalize',
              }}
              data-d={getKey(rs, '17ca53c3c3a14c88a003321c')}
            >
              <Text
                key='default-text-116'
                variants={b.getVariants(undefined)}
                className={b.getUniqueClassName()}
                style={undefined}
                text={'Human Design'}
                tag={'span'}
                data-d={getKey(rs, '17ca53c3c3a14c88a003321d')}
              />
            </Button>
            <Button
              key='button-38'
              variants={b.getVariants(undefined)}
              classes={b.getUniqueClassName()}
              color={'primary'}
              variant={'text'}
              sx={{
                'text-transform': 'capitalize',
              }}
              data-d={getKey(rs, '17ca53c3c3a14c88a003321e')}
            >
              <Text
                key='default-text-117'
                variants={b.getVariants(undefined)}
                className={b.getUniqueClassName()}
                style={undefined}
                text={'Metaphysical'}
                tag={'span'}
                data-d={getKey(rs, '17ca53c3c3a14c88a003321f')}
              />
            </Button>
            <Button
              key='button-39'
              variants={b.getVariants(undefined)}
              classes={b.getUniqueClassName()}
              color={'primary'}
              variant={'text'}
              sx={{
                'text-transform': 'capitalize',
              }}
              data-d={getKey(rs, '17ca53c3c3a14c88a0033220')}
            >
              <Text
                key='default-text-118'
                variants={b.getVariants(undefined)}
                className={b.getUniqueClassName()}
                style={undefined}
                text={'Psychology'}
                tag={'span'}
                data-d={getKey(rs, '17ca53c3c3a14c88a0033221')}
              />
            </Button>
            <Button
              key='button-40'
              variants={b.getVariants(undefined)}
              classes={b.getUniqueClassName()}
              color={'primary'}
              variant={'text'}
              sx={{
                'text-transform': 'capitalize',
              }}
              data-d={getKey(rs, '17ca53c3c3a14c88a0033222')}
            >
              <Text
                key='default-text-119'
                variants={b.getVariants(undefined)}
                className={b.getUniqueClassName()}
                style={undefined}
                text={'Cards'}
                tag={'span'}
                data-d={getKey(rs, '17ca53c3c3a14c88a0033223')}
              />
            </Button>
          </Grid>
          <Grid
            key='grid-136'
            variants={b.getVariants(undefined)}
            xs={8}
            md={3}
            justifyContents={'flex-end'}
            sx={{
              order: {
              xs: 2,
              md: 3,
            },
            }}
            data-d={getKey(rs, '17ca53c3c3a14c88a0033224')}
          >
            <Box
              key='box-39'
              variants={b.getVariants(undefined)}
              data-d={getKey(rs, '17ca53c3c3a14c88a0033225')}
            >
              <Grid
                key='grid-137'
                variants={b.getVariants(undefined)}
                container={true}
                justifyContent={'flex-end'}
                data-d={getKey(rs, '17ca53c3c3a14c88a0033226')}
              >
                <Grid
                  key='grid-138'
                  variants={b.getVariants(undefined)}
                  item={true}
                  data-d={getKey(rs, '17ca53c3c3a14c88a0033227')}
                >
                  <FormControl
                    key='form-control-3'
                    variants={b.getVariants(undefined)}
                    variant={'outlined'}
                    size={'small'}
                    color={'primary'}
                    data-d={getKey(rs, '17ca53c3c3a14c88a0033228')}
                  >
                    <OutlinedInput
                      key='outlined-input-3'
                      variants={b.getVariants(undefined)}
                      placeholder={'Search...'}
                      startAdornment={undefined}
                      type={'search'}
                      sx={{
                        '& MuiOutlinedInput-notchedOutline': {
                        borderColor: 'primary.main',
                      },
                        backgroundColor: 'rgba(66, 165, 245, 0.05)',
                        borderColor: 'primary.main',
                      }}
                      endAdornment={(Outlinedinput3BaseEndAdornment())}
                      data-d={getKey(rs, '17ca53c3c3a14c88a0033229')}
                    />
                  </FormControl>
                </Grid>
              </Grid>
            </Box>
          </Grid>
        </Grid>
      </Grid>
    ]);
  };
  ;
