/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
import React from 'react';
import * as b from '@clutch-creator/bridge';
import Card from '@clutch-marketplace/react-bootstrap/dist/cjs/components/Card';
import CardImg from '@clutch-marketplace/react-bootstrap/dist/cjs/components/CardImg';
import CardBody from '@clutch-marketplace/react-bootstrap/dist/cjs/components/CardBody';
import CardTitle from '@clutch-marketplace/react-bootstrap/dist/cjs/components/CardTitle';
import Text from '@clutch-marketplace/web-elements/dist/cjs/components/Text';
import CardSubtitle from '@clutch-marketplace/react-bootstrap/dist/cjs/components/CardSubtitle';
import Icon from '@clutch-marketplace/heroicons/dist/cjs/components/Icon';
import CardText from '@clutch-marketplace/react-bootstrap/dist/cjs/components/CardText';
import CardLink from '@clutch-marketplace/react-bootstrap/dist/cjs/components/CardLink';
import CardFooter from '@clutch-marketplace/react-bootstrap/dist/cjs/components/CardFooter';
import Badge from '@clutch-marketplace/react-bootstrap/dist/cjs/components/Badge';
import styles from './styles.module.css';

export default (props) => {
    const [report, getKey] = b.useReport(props);
    const { variants } = props;
    const variables = {};
  
    const rs = report(null, '61576d1465507b003260dadd', 'COMPOSITION', props, variables);
  
    return ([
      <Card
        key='filter-provider-card-17'
        variants={b.getVariants(undefined)}
        as={undefined}
        bg={undefined}
        body={undefined}
        border={undefined}
        text={undefined}
        className={b.mClassnames([
          b.getUniqueClassName(),
          styles['clutchClass11973'],
        ])}
        style={undefined}
        data-d={getKey(rs, '61576d1465507b003260dad4')}
      >
        <CardImg
          key='default-CardImg-28'
          variants={b.getVariants(undefined)}
          as={undefined}
          variant={undefined}
          src={'https://mzlzqjzvhavxetaoqwde.supabase.in/storage/v1/object/sign/profile-images/Erin Claire Jones.jpg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwcm9maWxlLWltYWdlcy9FcmluIENsYWlyZSBKb25lcy5qcGciLCJpYXQiOjE2MzI1MjMyNzksImV4cCI6MTk0Nzg4MzI3OX0.RxuZpRF8NZj8MPpFP5ngP6VGlInLonXuCmNaJh95P70'}
          className={b.mClassnames([
            b.getUniqueClassName(),
            styles['clutchClass11957'],
          ])}
          style={undefined}
          data-d={getKey(rs, '61576d1465507b003260dad2')}
        />
        <CardBody
          key='default-CardBody-41'
          variants={b.getVariants(undefined)}
          as={undefined}
          className={b.getUniqueClassName()}
          style={undefined}
          data-d={getKey(rs, '61576d1465507b003260dad3')}
        >
          <CardTitle
            key='default-CardTitle-30'
            variants={b.getVariants(undefined)}
            className={b.getUniqueClassName()}
            style={undefined}
            data-d={getKey(rs, '61576d1465507b003260dad5')}
          >
            <Text
              key='default-text-502'
              variants={b.getVariants(undefined)}
              className={b.getUniqueClassName()}
              style={undefined}
              text={'Erin Claire Jones'}
              tag={'span'}
              data-d={getKey(rs, '61576d1465507b003260dad6')}
            />
          </CardTitle>
          <CardSubtitle
            key='default-CardSubtitle-1'
            variants={b.getVariants(undefined)}
            className={b.getUniqueClassName()}
            style={undefined}
            data-d={getKey(rs, '61576d1465507b003260dae7')}
          >
            <Icon
              key='Heroicon-solid-1'
              variants={b.getVariants(undefined)}
              name={'star'}
              solid={true}
              color={'grey'}
              size={24}
              data-d={getKey(rs, '61576d1465507b003260dae8')}
            />
            <Icon
              key='Heroicon-solid-5'
              variants={b.getVariants(undefined)}
              name={'star'}
              solid={true}
              color={'grey'}
              size={24}
              data-d={getKey(rs, '61576d1465507b003260daec')}
            />
            <Icon
              key='Heroicon-solid-4'
              variants={b.getVariants(undefined)}
              name={'star'}
              solid={true}
              color={'grey'}
              size={24}
              data-d={getKey(rs, '61576d1465507b003260daeb')}
            />
            <Icon
              key='Heroicon-solid-3'
              variants={b.getVariants(undefined)}
              name={'star'}
              solid={true}
              color={'grey'}
              size={24}
              data-d={getKey(rs, '61576d1465507b003260daea')}
            />
            <Icon
              key='Heroicon-solid-2'
              variants={b.getVariants(undefined)}
              name={'star'}
              solid={true}
              color={'grey'}
              size={24}
              data-d={getKey(rs, '61576d1465507b003260dae9')}
            />
          </CardSubtitle>
          <CardText
            key='default-CardText-30'
            variants={b.getVariants(undefined)}
            className={b.getUniqueClassName()}
            style={undefined}
            data-d={getKey(rs, '61576d1465507b003260dad8')}
          >
            <Text
              key='default-text-511'
              variants={b.getVariants(undefined)}
              className={b.getUniqueClassName()}
              style={undefined}
              text={'As a Human Design Guide & Leadership Coach, I offer you a blueprint to how you operate so you can perform at the top of your personal and professional game.'}
              tag={'span'}
              data-d={getKey(rs, '61576d1465507b003260dad9')}
            />
          </CardText>
          <CardLink
            key='default-CardLink-9'
            variants={b.getVariants(undefined)}
            href={undefined}
            className={b.getUniqueClassName()}
            style={undefined}
            data-d={getKey(rs, '61576d1465507b003260dada')}
          >
            <Text
              key='default-text-518'
              variants={b.getVariants(undefined)}
              className={b.getUniqueClassName()}
              style={undefined}
              text={undefined}
              tag={'span'}
              data-d={getKey(rs, '61576d1465507b003260dad7')}
            />
          </CardLink>
        </CardBody>
        <CardFooter
          key='default-CardFooter-1'
          variants={b.getVariants(undefined)}
          className={b.mClassnames([
            b.getUniqueClassName(),
            styles['clutchClass11972'],
          ])}
          style={undefined}
          data-d={getKey(rs, '61576d1465507b003260dae6')}
        >
          <Badge
            key='default-Badge-2'
            variants={b.getVariants(undefined)}
            as={undefined}
            pill={false}
            className={b.mClassnames([
              b.getUniqueClassName(),
              'mr-1',
            ])}
            style={undefined}
            variant={'info'}
            data-d={getKey(rs, '61576d1465507b003260dadb')}
          >
            <Text
              key='default-text-5'
              variants={b.getVariants(undefined)}
              className={b.getUniqueClassName()}
              style={undefined}
              text={'Human Design'}
              tag={'span'}
              data-d={getKey(rs, '61576d1465507b003260dadc')}
            />
          </Badge>
          <Badge
            key='default-Badge-4'
            variants={b.getVariants(undefined)}
            as={undefined}
            pill={false}
            className={b.mClassnames([
              b.getUniqueClassName(),
              'mr-1',
            ])}
            style={undefined}
            variant={'danger'}
            data-d={getKey(rs, '61576d1465507b003260daef')}
          >
            <Text
              key='default-text-7'
              variants={b.getVariants(undefined)}
              className={b.getUniqueClassName()}
              style={undefined}
              text={'Courses'}
              tag={'span'}
              data-d={getKey(rs, '61576d1465507b003260daf0')}
            />
          </Badge>
          <Badge
            key='default-Badge-3'
            variants={b.getVariants(undefined)}
            as={undefined}
            pill={false}
            className={b.getUniqueClassName()}
            style={undefined}
            variant={'success'}
            data-d={getKey(rs, '61576d1465507b003260daed')}
          >
            <Text
              key='default-text-6'
              variants={b.getVariants(undefined)}
              className={b.getUniqueClassName()}
              style={undefined}
              text={'Media'}
              tag={'span'}
              data-d={getKey(rs, '61576d1465507b003260daee')}
            />
          </Badge>
        </CardFooter>
      </Card>
    ]);
  };
  ;
