/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
import React from 'react';
import * as b from '@clutch-creator/bridge';
import MUIApp from '../../../components/MUI App';

export default (props) => {
    const [report, getKey] = b.useReport(props);
    const { variants } = props;
    const variables = {};
  
    const rs = report(null, '17c3e42df5814c88a0033004', 'COMPOSITION', props, variables);
  
    return ([
      <MUIApp
        key='mui-app-1'
        variants={b.getVariants(undefined)}
        data-d={getKey(rs, '17c3e4593bd14c88a0033011')}
      >
        {null}
      </MUIApp>
    ]);
  };
  ;
