/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
import React from 'react';
import useComposition from './composition';

export default function Frame(props) {
  const composition = useComposition(props);

  return composition || null;
}
