/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
import React from 'react';
import * as b from '@clutch-creator/bridge';
import Box from '../Box';
import Grid from '../Grid';
import Image from '@clutch-marketplace/react-bootstrap/dist/cjs/components/Image';
import Typography from '../Typography';
import Text from '@clutch-marketplace/web-elements/dist/cjs/components/Text';
import Stack from '../Stack';
import Button from '../Button';
import styles from './styles.module.css';

export default (props) => {
    const [report, getKey] = b.useReport(props);
    const { variants } = props;
    const variables = {};
  
    const rs = report(null, '17c71bd354914c88a0033059', 'COMPOSITION', props, variables);
  
    return ([
      <Box
        key='box-6'
        variants={b.getVariants(undefined)}
        sx={{
          bgcolor: '#fdfbf7',
        }}
        data-d={getKey(rs, '17c5d74e40c14c88a003304d')}
      >
        <Grid
          key='grid-6'
          variants={b.getVariants(undefined)}
          container={true}
          justifyContent={'center'}
          data-d={getKey(rs, '17c6232acf814c88a0033000')}
        >
          <Grid
            key='grid-1'
            variants={b.getVariants(undefined)}
            container={true}
            classes={b.getUniqueClassName()}
            sx={undefined}
            maxWidth={1680}
            data-d={getKey(rs, '17c6113fb0514c88a0033000')}
          >
            <Grid
              key='grid-2'
              variants={b.getVariants(undefined)}
              direction={{
                xs: 'row',
                sm: 'row-reverse',
              }}
              container={true}
              data-d={getKey(rs, '17c611b058814c88a0033016')}
            >
              <Grid
                key='grid-4'
                variants={b.getVariants(undefined)}
                item={true}
                sx={{
                  bgcolor: '#fdfbf7',
                  p: {
                  xs: 4,
                  sm: 2,
                  md: 4,
                },
                }}
                xs={12}
                sm={5}
                justifyContent={{
                  sm: 'center',
                  md: 'flex-end',
                }}
                container={true}
                lg={6}
                data-d={getKey(rs, '17c615e5de814c88a00330d2')}
              >
                <Grid
                  key='grid-5'
                  variants={b.getVariants(undefined)}
                  item={false}
                  sx={{
                    mr: {
                    md: 5,
                    lg: 10,
                  },
                    justify: 'center',
                  }}
                  alignItems={'center'}
                  container={true}
                  justifyContent={{
                    sm: 'center',
                    md: 'flex-end',
                  }}
                  direction={'column'}
                  data-d={getKey(rs, '17c620ea38414c88a0033058')}
                >
                  <Image
                    key='shot-content-image-1'
                    variants={b.getVariants(undefined)}
                    src={'https://images.prismic.io/luminate/143d9333-8d56-450b-9064-218a6f1e30ff_Earth500px.png'}
                    fluid={undefined}
                    rounded={undefined}
                    roundedCircle={undefined}
                    thumbnail={undefined}
                    alt={undefined}
                    height={undefined}
                    width={undefined}
                    className={b.mClassnames([
                      b.getUniqueClassName(),
                      styles['clutchClass12028'],
                    ])}
                    style={undefined}
                    data-d={getKey(rs, '17c616c8ac814c88a00330f2')}
                  />
                </Grid>
              </Grid>
              <Grid
                key='grid-3'
                variants={b.getVariants(undefined)}
                item={true}
                xs={12}
                sm={7}
                sx={{
                  bgcolor: '#fdfbf7',
                  padding: 4,
                  pl: {
                  md: '10%',
                  lg: '15%',
                  xl: 30,
                },
                  pt: {
                  xs: '0',
                  sm: 4,
                },
                }}
                direction={'column'}
                container={true}
                justifyContent={'center'}
                lg={6}
                data-d={getKey(rs, '17c6152eeee14c88a0033079')}
              >
                <Grid
                  key='grid-14'
                  variants={b.getVariants(undefined)}
                  item={true}
                  sx={{
                    mb: 2,
                  }}
                  data-d={getKey(rs, '17c61f6324414c88a003301f')}
                >
                  <Typography
                    key='typography-1'
                    variants={b.getVariants(undefined)}
                    sx={{
                      typography: {
                      xs: 'h4',
                      lg: 'h3',
                    },
                      textAlign: {
                      xs: 'center',
                      sm: 'left',
                    },
                      fontWeight: {
                      xs: '500',
                      lg: '500',
                    },
                    }}
                    data-d={getKey(rs, '17c61e595df14c88a0033105')}
                  >
                    <Text
                      key='default-text-29'
                      variants={b.getVariants(undefined)}
                      className={b.getUniqueClassName()}
                      style={undefined}
                      text={'Discover a community from around the world'}
                      tag={undefined}
                      data-d={getKey(rs, '17c61f6e79f14c88a0033022')}
                    />
                  </Typography>
                </Grid>
                <Grid
                  key='grid-13'
                  variants={b.getVariants(undefined)}
                  item={true}
                  sx={{
                    mb: 2,
                  }}
                  data-d={getKey(rs, '17c615e692e14c88a00330e4')}
                >
                  <Typography
                    key='typography-2'
                    variants={b.getVariants(undefined)}
                    gutterBottom={false}
                    sx={{
                      typography: {
                      xs: 'body1',
                      lg: 'subtitle',
                    },
                      textAlign: {
                      xs: 'center',
                      sm: 'left',
                    },
                    }}
                    data-d={getKey(rs, '17c61ea377314c88a0033117')}
                  >
                    <Text
                      key='default-text-30'
                      variants={b.getVariants(undefined)}
                      className={b.getUniqueClassName()}
                      style={undefined}
                      text={'Luminate is the leading destination to find & showcase providers, services and resources to assist you on your personal journey'}
                      tag={undefined}
                      data-d={getKey(rs, '17c61f7905514c88a0033025')}
                    />
                  </Typography>
                </Grid>
                <Grid
                  key='grid-12'
                  variants={b.getVariants(undefined)}
                  item={true}
                  alignItems={'center'}
                  data-d={getKey(rs, '17c615e662114c88a00330e2')}
                >
                  <Stack
                    key='stack-1'
                    variants={b.getVariants(undefined)}
                    direction={'row'}
                    justifyContent={{
                      xs: 'center',
                      sm: 'flex-start',
                    }}
                    data-d={getKey(rs, '17c62747b6914c88a0033015')}
                  >
                    <Button
                      key='button-6'
                      variants={b.getVariants(undefined)}
                      variant={'contained'}
                      data-d={getKey(rs, '17c61eb2e8414c88a0033123')}
                    >
                      <Text
                        key='default-text-19'
                        variants={b.getVariants(undefined)}
                        className={b.getUniqueClassName()}
                        style={undefined}
                        text={'Sign Up'}
                        tag={'span'}
                        data-d={getKey(rs, '17c61f150b414c88a0033000')}
                      />
                    </Button>
                  </Stack>
                </Grid>
              </Grid>
            </Grid>
          </Grid>
        </Grid>
      </Box>
    ]);
  };
  ;
