/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
import React from 'react';
import * as b from '@clutch-creator/bridge';
import Grid from '../Grid';
import Typography from '../Typography';
import Text from '@clutch-marketplace/web-elements/dist/cjs/components/Text';
import Hook from '@clutch-marketplace/logic/dist/cjs/components/Hook';
import EventsScrollHookBaseHookModule from './logic/eventsScrollHook/base-hookmodule.js';
import Box from '../Box';
import Icon from '../Icon';
import CardEventHomepage from '../Card - Event Homepage';
import CardHomepageEndCard from '../Card - Homepage End Card';

export default (props) => {
    const [report, getKey] = b.useReport(props);
    const { variants } = props;
    const variables = {};
  
    const rs = report(null, '17c9ae2c03f14c88a0033001', 'COMPOSITION', props, variables);
  
    return ([
      <Grid
        key='grid-events-cards'
        variants={b.getVariants(undefined)}
        container={true}
        sx={{
          mb: 3,
        }}
        direction={'column'}
        data-d={getKey(rs, '17c99ff417114c88a00330e7')}
      >
        <Grid
          key='grid-42'
          variants={b.getVariants(undefined)}
          item={true}
          container={true}
          justifyContent={'space-between'}
          alignItems={'center'}
          data-d={getKey(rs, '17c99ff417114c88a00330e8')}
        >
          <Grid
            key='grid-98'
            variants={b.getVariants(undefined)}
            item={true}
            data-d={getKey(rs, '17c99ff417114c88a00330ec')}
          >
            <Typography
              key='typography-6'
              variants={b.getVariants(undefined)}
              gutterBottom={false}
              variant={'h5'}
              sx={{
                fontWeight: '500',
                color: 'primary.main',
                fontSize: '1.75rem',
                lineHeight: {
                xs: '1.5',
                md: '1.75',
              },
              }}
              data-d={getKey(rs, '17c99ff417114c88a00330ed')}
            >
              <Text
                key='default-text-46'
                variants={b.getVariants(undefined)}
                className={b.getUniqueClassName()}
                style={undefined}
                text={'Events'}
                tag={'span'}
                data-d={getKey(rs, '17c99ff417114c88a00330ee')}
              />
            </Typography>
          </Grid>
          <Grid
            key='grid-97'
            variants={b.getVariants(undefined)}
            item={true}
            data-d={getKey(rs, '17c99ff417114c88a00330e9')}
          >
            <Typography
              key='typography-24'
              variants={b.getVariants(undefined)}
              gutterBottom={false}
              variant={'subtitle2'}
              sx={{
                fontWeight: '600',
                ':hover': {
                color: 'primary.dark',
              },
                color: 'primary.main',
              }}
              data-d={getKey(rs, '17c99ff417114c88a00330ea')}
            >
              <Text
                key='default-text-58'
                variants={b.getVariants(undefined)}
                className={b.getUniqueClassName()}
                style={undefined}
                text={'SEE MORE'}
                data-d={getKey(rs, '17c99ff417114c88a00330eb')}
              />
            </Typography>
          </Grid>
        </Grid>
        <Grid
          key='grid-99'
          variants={b.getVariants(undefined)}
          item={true}
          container={true}
          data-d={getKey(rs, '17c99ff417114c88a00330ef')}
        >
          <Hook
            key='eventsScrollHook'
            variants={b.getVariants(undefined)}
            hookModule={EventsScrollHookBaseHookModule}
            arguments={[]}
            data-d={getKey(rs, '17c9ae2c03f14c88a0033002')}
          >
            {((r, v) => (...eventsScrollHookArgs) => {
              const newVariables = {};
            
              let variables = {
                ...v,
                ...newVariables
              };
            
              const rs = report(r, '17c9ae2c03f14c88a0033002', '1791eb63ceefae252001b80a', eventsScrollHookArgs, newVariables);
            
              const renderFn = [
                <Box
                  key='box-26'
                  variants={b.getVariants(undefined)}
                  sx={{
                    ml: {
                    xs: -2,
                    sm: -5,
                    md: 0,
                  },
                    mr: {
                    xs: -2,
                    sm: -5,
                    md: 0,
                  },
                    overflow: 'auto',
                    display: 'flex',
                  }}
                  data-d={getKey(rs, '17c9ae2c03f14c88a0033003')}
                >
                  <Box
                    key='box-33'
                    variants={b.getVariants(undefined)}
                    sx={{
                      width: 100,
                      backgroundColor: 'rgba(224, 224, 224, 0.7)',
                      borderRadius: 1,
                      display: {
                      xs: 'none',
                      md: 'flex',
                    },
                      alignItems: 'center',
                      justifyContent: 'center',
                      'z-index': '100',
                      mb: '5px',
                    }}
                    onClick={b.tryCatch(() => (() => b.propertyBind(eventsScrollHookArgs, ['0','current']).scrollLeft -= 325))}
                    data-d={getKey(rs, '17c9ae2c04014c88a0033012')}
                  >
                    <Icon
                      key='icon-17'
                      variants={b.getVariants(undefined)}
                      sx={{
                        color: 'grey.800',
                      }}
                      data-d={getKey(rs, '17c9ae2c04014c88a0033013')}
                    >
                      {'chevron_left'}
                    </Icon>
                  </Box>
                  <Grid
                    key='grid-70'
                    variants={b.getVariants(undefined)}
                    display={'grid'}
                    sx={{
                      ml: {
                      xs: 0,
                      md: -4,
                    },
                      mr: {
                      xs: 0,
                      md: -4,
                    },
                    }}
                    data-d={getKey(rs, '17c9ae2c03f14c88a0033004')}
                  >
                    <Grid
                      key='eventsScroll'
                      variants={b.getVariants(undefined)}
                      container={false}
                      sx={{
                        display: 'grid',
                        'grid-gap': '20px',
                        'overflow-x': 'scroll',
                        'scroll-snap-type': 'x proximity',
                        'grid-auto-flow': 'column',
                        'grid-auto-columns': undefined,
                        p: {
                        xs: '10px 15px 20px 15px',
                        md: '10px 0px 20px 40px',
                      },
                        '::-webkit-scrollbar': {
                        display: 'none',
                      },
                        '-ms-overflow-style': 'none',
                        'scroll-behavior': 'smooth',
                        'grid-auto-rows': 'auto',
                      }}
                      ref={b.tryCatch(() => (b.propertyBind(eventsScrollHookArgs, ['0'])))}
                      data-d={getKey(rs, '17c9ae2c03f14c88a0033005')}
                    >
                      <CardEventHomepage
                        key='card-event-homepage-1'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17c9ae518c314c88a003304c')}
                      />
                      <CardEventHomepage
                        key='card-event-homepage-8'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17c9ae5444314c88a0033053')}
                      />
                      <CardEventHomepage
                        key='card-event-homepage-7'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17c9ae5433414c88a0033052')}
                      />
                      <CardEventHomepage
                        key='card-event-homepage-6'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17c9ae5425e14c88a0033051')}
                      />
                      <CardEventHomepage
                        key='card-event-homepage-5'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17c9ae5416314c88a0033050')}
                      />
                      <CardEventHomepage
                        key='card-event-homepage-4'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17c9ae5407414c88a003304f')}
                      />
                      <CardEventHomepage
                        key='card-event-homepage-3'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17c9ae53f7414c88a003304e')}
                      />
                      <CardEventHomepage
                        key='card-event-homepage-2'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17c9ae53e5814c88a003304d')}
                      />
                      <CardHomepageEndCard
                        key='card-provider-homepage-end-card-4'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17c9ae2c03f14c88a0033006')}
                      />
                    </Grid>
                  </Grid>
                  <Box
                    key='box-34'
                    variants={b.getVariants(undefined)}
                    sx={{
                      width: 100,
                      backgroundColor: 'rgba(224, 224, 224, 0.7)',
                      borderRadius: 1,
                      display: {
                      xs: 'none',
                      md: 'flex',
                    },
                      alignItems: 'center',
                      justifyContent: 'center',
                      'z-index': '100',
                      mb: '5px',
                    }}
                    onClick={b.tryCatch(() => (() => b.propertyBind(eventsScrollHookArgs, ['0','current']).scrollLeft += 325))}
                    data-d={getKey(rs, '17c9ae2c04014c88a0033014')}
                  >
                    <Icon
                      key='icon-18'
                      variants={b.getVariants(undefined)}
                      sx={{
                        color: 'grey.800',
                      }}
                      data-d={getKey(rs, '17c9ae2c04014c88a0033015')}
                    >
                      {'chevron_right'}
                    </Icon>
                  </Box>
                </Box>
              ];
            
              return typeof renderFn === 'function' ? renderFn(...eventsScrollHookArgs) : renderFn;
            })(rs, variables)}
          </Hook>
        </Grid>
      </Grid>
    ]);
  };
  ;
