/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
import React from 'react';
import * as b from '@clutch-creator/bridge';
import Card from '../Card';
import CardActionArea from '../Card Action Area';
import CardContent from '../Card Content';
import Grid from '../Grid';
import Typography from '../Typography';
import Text from '@clutch-marketplace/web-elements/dist/cjs/components/Text';
import Button from '../Button';

export default (props) => {
    const [report, getKey] = b.useReport(props);
    const { variants } = props;
    const variables = {};
  
    const rs = report(null, '17c8fc73d0b14c88a0033001', 'COMPOSITION', props, variables);
  
    return ([
      <Card
        key='card-10'
        variants={b.getVariants(undefined)}
        sx={{
          width: 300,
          height: 450,
          mr: 6,
        }}
        raised={true}
        data-d={getKey(rs, '17c8fc73d0b14c88a0033002')}
      >
        <CardActionArea
          key='card-action-area-2'
          variants={b.getVariants(undefined)}
          sx={{
            height: '100%',
          }}
          data-d={getKey(rs, '17c8fc73d0c14c88a003300e')}
        >
          <CardContent
            key='card-content-12'
            variants={b.getVariants(undefined)}
            sx={{
              height: '100%',
            }}
            data-d={getKey(rs, '17c8fc73d0c14c88a0033019')}
          >
            <Grid
              key='grid-21'
              variants={b.getVariants(undefined)}
              container={true}
              direction={'column'}
              rowGap={2}
              sx={{
                height: '100%',
              }}
              justifyContent={'center'}
              alignItems={'center'}
              data-d={getKey(rs, '17c8fc73d0c14c88a003301a')}
            >
              <Grid
                key='grid-56'
                variants={b.getVariants(undefined)}
                container={true}
                justifyContent={'center'}
                data-d={getKey(rs, '17c8fc73d0c14c88a003301b')}
              >
                <Typography
                  key='typography-49'
                  variants={b.getVariants(undefined)}
                  variant={'h5'}
                  textAlign={'center'}
                  data-d={getKey(rs, '17c8fc73d0c14c88a003301c')}
                >
                  <Text
                    key='default-text-104'
                    variants={b.getVariants(undefined)}
                    className={b.getUniqueClassName()}
                    style={undefined}
                    text={"There's more just waiting to be discovered!"}
                    data-d={getKey(rs, '17c8fc73d0c14c88a003301d')}
                  />
                </Typography>
              </Grid>
              <Grid
                key='grid-57'
                variants={b.getVariants(undefined)}
                container={true}
                justifyContent={'center'}
                data-d={getKey(rs, '17c8fc73d0c14c88a003301e')}
              >
                <Button
                  key='button-13'
                  variants={b.getVariants(undefined)}
                  variant={'contained'}
                  data-d={getKey(rs, '17c8fd1c2b314c88a0033058')}
                >
                  <Text
                    key='default-text-1'
                    variants={b.getVariants(undefined)}
                    className={b.getUniqueClassName()}
                    style={undefined}
                    text={'Find More'}
                    data-d={getKey(rs, '17c8fd224e214c88a0033061')}
                  />
                </Button>
              </Grid>
            </Grid>
          </CardContent>
        </CardActionArea>
      </Card>
    ]);
  };
  ;
