/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
import React from 'react';
import * as b from '@clutch-creator/bridge';
import Card from '../Card';
import CardActionArea from '../Card Action Area';
import CardMedia from '../Card Media';
import CardContent from '../Card Content';
import Grid from '../Grid';
import Typography from '../Typography';
import Text from '@clutch-marketplace/web-elements/dist/cjs/components/Text';
import Chip from '../Chip';
import CardActions from '../Card Actions';
import Box from '../Box';
import State from '@clutch-marketplace/logic/dist/cjs/components/State';
import Rating from '../Rating';
import Button from '../Button';
import styles from './styles.module.css';

export default (props) => {
    const [report, getKey] = b.useReport(props);
    const { variants } = props;
    const variables = {};
  
    const rs = report(null, '17c9ae4f83314c88a0033021', 'COMPOSITION', props, variables);
  
    return ([
      <Card
        key='card-13'
        variants={b.getVariants(undefined)}
        sx={{
          width: 300,
          height: 450,
        }}
        raised={true}
        data-d={getKey(rs, '17c9ae4f83314c88a0033022')}
      >
        <CardActionArea
          key='card-action-area-5'
          variants={b.getVariants(undefined)}
          data-d={getKey(rs, '17c9ae4f83314c88a003302e')}
        >
          <CardMedia
            key='card-media-11'
            variants={b.getVariants(undefined)}
            image={'https://humandesignconference.com/wp-content/uploads/2020/09/HDConference_Logo-1.png'}
            component={'img'}
            sx={{
              maxHeight: 150,
              objectFit: 'contain',
            }}
            data-d={getKey(rs, '17c9ae4f83414c88a0033047')}
          />
          <CardContent
            key='card-content-14'
            variants={b.getVariants(undefined)}
            sx={{
              height: 254,
            }}
            data-d={getKey(rs, '17c9ae4f83314c88a003302f')}
          >
            <Grid
              key='grid-105'
              variants={b.getVariants(undefined)}
              container={true}
              direction={'column'}
              alignItems={'flex-start'}
              rowSpacing={1.5}
              data-d={getKey(rs, '17c9ae4f83314c88a0033030')}
            >
              <Grid
                key='grid-106'
                variants={b.getVariants(undefined)}
                direction={'column'}
                container={true}
                item={true}
                data-d={getKey(rs, '17c9ae4f83314c88a0033031')}
              >
                <Grid
                  key='grid-107'
                  variants={b.getVariants(undefined)}
                  item={true}
                  data-d={getKey(rs, '17c9ae4f83314c88a0033032')}
                >
                  <Typography
                    key='typography-26'
                    variants={b.getVariants(undefined)}
                    sx={{
                      pb: 0.5,
                      fontSize: 18,
                      fontWeight: '400',
                      lineHeight: 1.25,
                    }}
                    data-d={getKey(rs, '17c9ae4f83314c88a0033033')}
                  >
                    <Text
                      key='default-text-75'
                      variants={b.getVariants(undefined)}
                      className={b.getUniqueClassName()}
                      style={undefined}
                      text={'Human Design Conference'}
                      data-d={getKey(rs, '17c9ae4f83314c88a0033034')}
                    />
                  </Typography>
                </Grid>
                <Grid
                  key='grid-112'
                  variants={b.getVariants(undefined)}
                  item={true}
                  container={true}
                  justifyContent={'space-between'}
                  direction={'column'}
                  data-d={getKey(rs, '17c9ae4f83414c88a003303c')}
                >
                  <Grid
                    key='grid-113'
                    variants={b.getVariants(undefined)}
                    item={true}
                    data-d={getKey(rs, '17c9ae4f83414c88a003303d')}
                  >
                    <Typography
                      key='typography-27'
                      variants={b.getVariants(undefined)}
                      variant={'subtitle2'}
                      sx={{
                        color: 'grey.700',
                        pb: 1,
                      }}
                      data-d={getKey(rs, '17c9ae4f83414c88a003303e')}
                    >
                      <Text
                        key='default-text-76'
                        variants={b.getVariants(undefined)}
                        className={b.getUniqueClassName()}
                        style={undefined}
                        text={'Quantum Human Design™'}
                        data-d={getKey(rs, '17c9ae4f83414c88a003303f')}
                      />
                    </Typography>
                  </Grid>
                  <Grid
                    key='grid-117'
                    variants={b.getVariants(undefined)}
                    item={true}
                    container={true}
                    justifyContent={'space-between'}
                    data-d={getKey(rs, '17c9aee99a514c88a003305d')}
                  >
                    <Typography
                      key='typography-29'
                      variants={b.getVariants(undefined)}
                      variant={'body2'}
                      sx={{
                        color: 'grey.700',
                        pb: 1,
                      }}
                      data-d={getKey(rs, '17c9aee99a514c88a003305f')}
                    >
                      <Text
                        key='default-text-78'
                        variants={b.getVariants(undefined)}
                        className={b.getUniqueClassName()}
                        style={undefined}
                        text={'10/19/21 - 10/20/21'}
                        data-d={getKey(rs, '17c9aee99a514c88a0033060')}
                      />
                    </Typography>
                    <Grid
                      key='grid-114'
                      variants={b.getVariants(undefined)}
                      item={true}
                      data-d={getKey(rs, '17c9ae4f83414c88a0033040')}
                    >
                      <Typography
                        key='typography-28'
                        variants={b.getVariants(undefined)}
                        variant={'subtitle2'}
                        sx={{
                          pb: 1,
                          fontWeight: 700,
                        }}
                        data-d={getKey(rs, '17c9ae4f83414c88a0033041')}
                      >
                        <Text
                          key='default-text-77'
                          variants={b.getVariants(undefined)}
                          className={b.getUniqueClassName()}
                          style={undefined}
                          text={'$365'}
                          data-d={getKey(rs, '17c9ae4f83414c88a0033042')}
                        />
                      </Typography>
                    </Grid>
                  </Grid>
                </Grid>
                <Grid
                  key='grid-108'
                  variants={b.getVariants(undefined)}
                  container={true}
                  direction={'row'}
                  spacing={undefined}
                  justifyContent={'space-between'}
                  alignItems={'center'}
                  rowSpacing={1}
                  data-d={getKey(rs, '17c9ae4f83314c88a0033035')}
                >
                  <Grid
                    key='grid-109'
                    variants={b.getVariants(undefined)}
                    item={true}
                    data-d={getKey(rs, '17c9ae4f83314c88a0033036')}
                  >
                    <Chip
                      key='chip-5'
                      variants={b.getVariants(undefined)}
                      label={'Human Design'}
                      size={'small'}
                      color={undefined}
                      data-d={getKey(rs, '17c9ae4f83314c88a0033037')}
                    />
                  </Grid>
                  <Grid
                    key='grid-111'
                    variants={b.getVariants(undefined)}
                    item={true}
                    data-d={getKey(rs, '17c9ae4f83414c88a003303a')}
                  >
                    <Chip
                      key='chip-7'
                      variants={b.getVariants(undefined)}
                      label={'2 Days'}
                      size={'small'}
                      color={undefined}
                      data-d={getKey(rs, '17c9ae4f83414c88a003303b')}
                    />
                  </Grid>
                  <Grid
                    key='grid-110'
                    variants={b.getVariants(undefined)}
                    item={true}
                    data-d={getKey(rs, '17c9ae4f83314c88a0033038')}
                  >
                    <Chip
                      key='chip-6'
                      variants={b.getVariants(undefined)}
                      label={'In Person'}
                      size={'small'}
                      color={undefined}
                      data-d={getKey(rs, '17c9ae4f83314c88a0033039')}
                    />
                  </Grid>
                </Grid>
              </Grid>
              <Grid
                key='grid-115'
                variants={b.getVariants(undefined)}
                container={true}
                direction={'column'}
                rowGap={1}
                sx={{
                  height: undefined,
                }}
                item={true}
                data-d={getKey(rs, '17c9ae4f83414c88a0033043')}
              >
                <Grid
                  key='grid-116'
                  variants={b.getVariants(undefined)}
                  container={true}
                  data-d={getKey(rs, '17c9ae4f83414c88a0033044')}
                >
                  <Typography
                    key='typography-54'
                    variants={b.getVariants(undefined)}
                    variant={'body2'}
                    data-d={getKey(rs, '17c9ae4f83414c88a0033045')}
                  >
                    <Text
                      key='default-text-111'
                      variants={b.getVariants(undefined)}
                      className={b.mClassnames([
                        b.getUniqueClassName(),
                        styles['clutchClass12071'],
                      ])}
                      style={undefined}
                      text={'Dig into the history and story of Human Design and begin exploring how Human Design can help us interpret our future and lay the foundation for building an equitable, sustainable and peaceful future.'}
                      tag={'p'}
                      data-d={getKey(rs, '17c9ae4f83414c88a0033046')}
                    />
                  </Typography>
                </Grid>
              </Grid>
            </Grid>
          </CardContent>
        </CardActionArea>
        <CardActions
          key='card-actions-12'
          variants={b.getVariants(undefined)}
          data-d={getKey(rs, '17c9ae4f83314c88a0033023')}
        >
          <Grid
            key='grid-103'
            variants={b.getVariants(undefined)}
            container={true}
            data-d={getKey(rs, '17c9ae4f83314c88a0033024')}
          >
            <Grid
              key='grid-104'
              variants={b.getVariants(undefined)}
              container={true}
              justifyContent={'space-between'}
              alignItems={'center'}
              data-d={getKey(rs, '17c9ae4f83314c88a0033025')}
            >
              <Box
                key='box-35'
                variants={b.getVariants(undefined)}
                sx={{
                  display: 'flex',
                  alignItems: 'center',
                }}
                data-d={getKey(rs, '17c9ae4f83314c88a0033026')}
              >
                <State
                  key='number-state-12'
                  variants={b.getVariants(undefined)}
                  initialValue={4.65}
                  data-d={getKey(rs, '17c9ae4f83314c88a0033027')}
                >
                  {((r, v) => (...numberstate12Args) => {
                    const newVariables = {};
                  
                    let variables = {
                      ...v,
                      ...newVariables
                    };
                  
                    const rs = report(r, '17c9ae4f83314c88a0033027', '178bf970a34fae252001bf06', numberstate12Args, newVariables);
                  
                    const renderFn = [
                      <Rating
                        key='rating-12'
                        variants={b.getVariants(undefined)}
                        size={'small'}
                        readOnly={true}
                        value={4.65}
                        precision={0.25}
                        data-d={getKey(rs, '17c9ae4f83314c88a0033028')}
                      />,
                      <Box
                        key='box-36'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17c9ae4f83314c88a0033029')}
                      >
                        <Typography
                          key='typography-53'
                          variants={b.getVariants(undefined)}
                          variant={'caption'}
                          sx={{
                            fontSize: '11px',
                            pl: 0.5,
                          }}
                          data-d={getKey(rs, '17c9ae4f83314c88a003302a')}
                        >
                          <Text
                            key='default-text-109'
                            variants={b.getVariants(undefined)}
                            className={b.getUniqueClassName()}
                            style={undefined}
                            text={b.tryCatch(() => ('(' + b.propertyBind(numberstate12Args, ['0','state']) + ')'))}
                            tag={false}
                            data-d={getKey(rs, '17c9ae4f83314c88a003302b')}
                          />
                        </Typography>
                      </Box>
                    ];
                  
                    return typeof renderFn === 'function' ? renderFn(...numberstate12Args) : renderFn;
                  })(rs, variables)}
                </State>
              </Box>
              <Button
                key='button-24'
                variants={b.getVariants(undefined)}
                variant={'text'}
                size={'small'}
                data-d={getKey(rs, '17c9ae4f83314c88a003302c')}
              >
                <Text
                  key='default-text-110'
                  variants={b.getVariants(undefined)}
                  className={b.getUniqueClassName()}
                  style={{
                    textTransform: 'capitalize',
                  }}
                  text={'Learn More'}
                  tag={'span'}
                  data-d={getKey(rs, '17c9ae4f83314c88a003302d')}
                />
              </Button>
            </Grid>
          </Grid>
        </CardActions>
      </Card>
    ]);
  };
  ;
