/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
import React from 'react';
import * as b from '@clutch-creator/bridge';
import Grid from '../Grid';
import Typography from '../Typography';
import Text from '@clutch-marketplace/web-elements/dist/cjs/components/Text';
import Hook from '@clutch-marketplace/logic/dist/cjs/components/Hook';
import CoursesScrollHookBaseHookModule from './logic/coursesScrollHook/base-hookmodule.js';
import Box from '../Box';
import Icon from '../Icon';
import CardCourseHomepage from '../Card - Course Homepage';
import CardHomepageEndCard from '../Card - Homepage End Card';

export default (props) => {
    const [report, getKey] = b.useReport(props);
    const { variants } = props;
    const variables = {};
  
    const rs = report(null, '17c8fdc0b7414c88a003308a', 'COMPOSITION', props, variables);
  
    return ([
      <Grid
        key='grid-courses-cards'
        variants={b.getVariants(undefined)}
        container={true}
        sx={{
          mb: 3,
        }}
        direction={'column'}
        item={true}
        xs={12}
        data-d={getKey(rs, '17ca86a986814c88a0033061')}
      >
        <Grid
          key='grid-69'
          variants={b.getVariants(undefined)}
          item={true}
          container={true}
          justifyContent={'space-between'}
          alignItems={'center'}
          data-d={getKey(rs, '17ca86a986814c88a0033062')}
        >
          <Grid
            key='grid-71'
            variants={b.getVariants(undefined)}
            item={true}
            data-d={getKey(rs, '17ca86a986814c88a0033063')}
          >
            <Typography
              key='typography-15'
              variants={b.getVariants(undefined)}
              gutterBottom={false}
              variant={'h5'}
              sx={{
                fontWeight: '500',
                color: 'primary.main',
                fontSize: '1.75rem',
                lineHeight: {
                xs: '1.5',
                md: '1.75',
              },
              }}
              data-d={getKey(rs, '17ca86a986814c88a0033064')}
            >
              <Text
                key='default-text-51'
                variants={b.getVariants(undefined)}
                className={b.getUniqueClassName()}
                style={undefined}
                text={'Courses'}
                tag={'span'}
                data-d={getKey(rs, '17ca86a986814c88a0033065')}
              />
            </Typography>
          </Grid>
          <Grid
            key='grid-100'
            variants={b.getVariants(undefined)}
            item={true}
            data-d={getKey(rs, '17ca86a986814c88a0033066')}
          >
            <Typography
              key='typography-25'
              variants={b.getVariants(undefined)}
              gutterBottom={false}
              variant={'subtitle2'}
              sx={{
                fontWeight: '500',
                ':hover': {
                color: 'primary.dark',
              },
                color: 'primary.main',
              }}
              data-d={getKey(rs, '17ca86a986814c88a0033067')}
            >
              <Text
                key='default-text-59'
                variants={b.getVariants(undefined)}
                className={b.getUniqueClassName()}
                style={undefined}
                text={'SEE MORE'}
                data-d={getKey(rs, '17ca86a986814c88a0033068')}
              />
            </Typography>
          </Grid>
        </Grid>
        <Grid
          key='grid-101'
          variants={b.getVariants(undefined)}
          item={true}
          container={true}
          data-d={getKey(rs, '17ca86a986814c88a0033069')}
        >
          <Hook
            key='coursesScrollHook'
            variants={b.getVariants(undefined)}
            hookModule={CoursesScrollHookBaseHookModule}
            arguments={[]}
            data-d={getKey(rs, '17ca86a986814c88a003306a')}
          >
            {((r, v) => (...coursesScrollHookArgs) => {
              const newVariables = {};
            
              let variables = {
                ...v,
                ...newVariables
              };
            
              const rs = report(r, '17ca86a986814c88a003306a', '1791eb63ceefae252001b80a', coursesScrollHookArgs, newVariables);
            
              const renderFn = [
                <Grid
                  key='grid-139'
                  variants={b.getVariants(undefined)}
                  sx={{
                    overflow: 'auto',
                    display: 'flex',
                    ml: {
                    xs: -2,
                    sm: -5,
                    md: 0,
                  },
                    mr: {
                    xs: -2,
                    sm: -5,
                    md: 0,
                  },
                  }}
                  data-d={getKey(rs, '17ca86a986814c88a003306c')}
                >
                  <Grid
                    key='grid-102'
                    variants={b.getVariants(undefined)}
                    sx={{
                      width: '36px',
                      display: {
                      xs: 'none',
                      md: 'flex',
                    },
                    }}
                    item={true}
                    container={true}
                    data-d={getKey(rs, '17ca86a986814c88a003306d')}
                  >
                    <Box
                      key='box-22'
                      variants={b.getVariants(undefined)}
                      sx={{
                        width: 36,
                        backgroundColor: 'rgba(224, 224, 224, 0.7)',
                        borderRadius: 1,
                        display: {
                        xs: 'none',
                        md: 'flex',
                      },
                        alignItems: 'center',
                        justifyContent: 'center',
                        'z-index': '100',
                        mb: '5px',
                      }}
                      onClick={b.tryCatch(() => (() => b.propertyBind(coursesScrollHookArgs, ['0','current']).scrollLeft -= 325))}
                      data-d={getKey(rs, '17ca86a986814c88a003306e')}
                    >
                      <Icon
                        key='icon-19'
                        variants={b.getVariants(undefined)}
                        sx={{
                          color: 'grey.800',
                        }}
                        data-d={getKey(rs, '17ca86a986814c88a003306f')}
                      >
                        {'chevron_left'}
                      </Icon>
                    </Box>
                  </Grid>
                  <Grid
                    key='grid-118'
                    variants={b.getVariants(undefined)}
                    display={'grid'}
                    sx={{
                      ml: {
                      xs: 0,
                      md: -4,
                    },
                      mr: {
                      xs: 0,
                      md: -4,
                    },
                    }}
                    item={true}
                    container={true}
                    data-d={getKey(rs, '17ca86a986814c88a0033070')}
                  >
                    <Grid
                      key='providerScroll-1'
                      variants={b.getVariants(undefined)}
                      container={true}
                      sx={{
                        display: 'grid',
                        'grid-gap': '20px',
                        'overflow-x': 'scroll',
                        'scroll-snap-type': 'x proximity',
                        'grid-auto-flow': 'column',
                        'grid-auto-columns': undefined,
                        p: {
                        xs: '10px 15px 20px 15px',
                        md: '10px 0px 20px 40px',
                      },
                        '::-webkit-scrollbar': {
                        display: 'none',
                      },
                        '-ms-overflow-style': 'none',
                        'scroll-behavior': 'smooth',
                        'grid-auto-rows': 'auto',
                      }}
                      ref={b.tryCatch(() => (b.propertyBind(coursesScrollHookArgs, ['0'])))}
                      data-d={getKey(rs, '17ca86a986814c88a0033071')}
                    >
                      <CardCourseHomepage
                        key='card-course-homepage-1'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17ca872a05514c88a0033082')}
                      />
                      <CardCourseHomepage
                        key='card-course-homepage-10'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17ca872b5d414c88a003308b')}
                      />
                      <CardCourseHomepage
                        key='card-course-homepage-9'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17ca872b4e114c88a003308a')}
                      />
                      <CardCourseHomepage
                        key='card-course-homepage-8'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17ca872b36b14c88a0033089')}
                      />
                      <CardCourseHomepage
                        key='card-course-homepage-7'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17ca872b23814c88a0033088')}
                      />
                      <CardCourseHomepage
                        key='card-course-homepage-6'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17ca872b13114c88a0033087')}
                      />
                      <CardCourseHomepage
                        key='card-course-homepage-5'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17ca872aff114c88a0033086')}
                      />
                      <CardCourseHomepage
                        key='card-course-homepage-4'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17ca872aef114c88a0033085')}
                      />
                      <CardCourseHomepage
                        key='card-course-homepage-3'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17ca872adf014c88a0033084')}
                      />
                      <CardCourseHomepage
                        key='card-course-homepage-2'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17ca872acf114c88a0033083')}
                      />
                      <CardHomepageEndCard
                        key='card-provider-homepage-end-card-5'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17ca86a986814c88a003307d')}
                      />
                    </Grid>
                  </Grid>
                  <Grid
                    key='grid-119'
                    variants={b.getVariants(undefined)}
                    sx={{
                      width: '36px',
                      display: {
                      xs: 'none',
                      md: 'flex',
                    },
                    }}
                    item={true}
                    container={true}
                    data-d={getKey(rs, '17ca86a986814c88a003307e')}
                  >
                    <Box
                      key='box-23'
                      variants={b.getVariants(undefined)}
                      sx={{
                        width: 100,
                        backgroundColor: 'rgba(224, 224, 224, 0.7)',
                        borderRadius: 1,
                        display: {
                        xs: 'none',
                        md: 'flex',
                      },
                        alignItems: 'center',
                        justifyContent: 'center',
                        'z-index': '100',
                        mb: '5px',
                      }}
                      onClick={b.tryCatch(() => (() => b.propertyBind(coursesScrollHookArgs, ['0','current']).scrollLeft += 325))}
                      data-d={getKey(rs, '17ca86a986814c88a003307f')}
                    >
                      <Icon
                        key='icon-20'
                        variants={b.getVariants(undefined)}
                        sx={{
                          color: 'grey.800',
                        }}
                        fontSize={''}
                        data-d={getKey(rs, '17ca86a986814c88a0033080')}
                      >
                        {'chevron_right'}
                      </Icon>
                    </Box>
                  </Grid>
                </Grid>
              ];
            
              return typeof renderFn === 'function' ? renderFn(...coursesScrollHookArgs) : renderFn;
            })(rs, variables)}
          </Hook>
        </Grid>
      </Grid>
    ]);
  };
  ;
