/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
import React from 'react';
import * as b from '@clutch-creator/bridge';
import Icon from '../Icon';

export default (props) => {
    const [report, getKey] = b.useReport(props);
    const { variants } = props;
    const variables = {};
  
    const rs = report(null, '17c4d79ba1214c88a0033038', 'COMPOSITION', props, variables);
  
    return ([
      <Icon
        key='icon-1'
        variants={b.getVariants(undefined)}
        data-d={getKey(rs, '17c51cb113214c88a0033015')}
      />
    ]);
  };
  ;
