/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
import React from 'react';
import * as b from '@clutch-creator/bridge';
import InputAdornment from '../InputAdornment';
import SearchIcon from '../SearchIcon';

export default (props) => {
    const [report, getKey] = b.useReport(props);
    const { variants } = props;
    const variables = {};
  
    const rs = report(null, '17c761e065314c88a00330d9', 'COMPOSITION', props, variables);
  
    return ([
      <InputAdornment
        key='input-adornment-1'
        variants={b.getVariants(undefined)}
        position={'start'}
        data-d={getKey(rs, '17c761bb65614c88a00330c7')}
      >
        <SearchIcon
          key='icon-search-1'
          variants={b.getVariants(undefined)}
          data-d={getKey(rs, '17c761d7f3a14c88a00330d5')}
        />
      </InputAdornment>
    ]);
  };
  ;
