/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
import React from 'react';
import * as b from '@clutch-creator/bridge';
import Card from '../Card';
import SpotifyPodcastEmbed from '../Spotify Podcast Embed';
import CardMedia from '../Card Media';
import CardActionArea from '../Card Action Area';
import CardContent from '../Card Content';
import Grid from '../Grid';
import Typography from '../Typography';
import Text from '@clutch-marketplace/web-elements/dist/cjs/components/Text';
import Chip from '../Chip';
import CardActions from '../Card Actions';
import Box from '../Box';
import State from '@clutch-marketplace/logic/dist/cjs/components/State';
import Rating from '../Rating';
import Button from '../Button';
import styles from './styles.module.css';

export default (props) => {
    const [report, getKey] = b.useReport(props);
    const { variants } = props;
    const variables = {};
  
    const rs = report(null, '17c901e62fe14c88a0033284', 'COMPOSITION', props, variables);
  
    return ([
      <Card
        key='card-12'
        variants={b.getVariants(undefined)}
        sx={{
          width: 300,
          height: 450,
        }}
        raised={true}
        data-d={getKey(rs, '17c901e62fe14c88a0033285')}
      >
        <SpotifyPodcastEmbed
          key='spotify-embed-1'
          variants={b.getVariants(undefined)}
          link={'https://open.spotify.com/show/3k2fpuQecYQBUr7zTgSNdZ?si=8f71aa392b194f16'}
          width={'100%'}
          height={155}
          data-d={getKey(rs, '17c902c322514c88a00332d5')}
        />
        {(false) ?   <CardMedia
          key='card-media-12'
          variants={b.getVariants(undefined)}
          image={'https://images.squarespace-cdn.com/content/v1/5a734c9af43b55b6cd5466a1/1542989568344-BVJ2RBYWUAMIDUF79HOJ/Inna+Shnayder+%40Inna.Shnayder-8+%283%29.jpg?format=300w'}
          component={'img'}
          sx={{
            maxHeight: 155,
          }}
          data-d={getKey(rs, '17c941faf1b14c88a0033000')}
        /> : null}
        <CardActionArea
          key='card-action-area-4'
          variants={b.getVariants(undefined)}
          data-d={getKey(rs, '17c901e62ff14c88a0033291')}
        >
          <CardContent
            key='card-content-13'
            variants={b.getVariants(undefined)}
            sx={{
              height: 245,
            }}
            data-d={getKey(rs, '17c901e62ff14c88a0033292')}
          >
            <Grid
              key='grid-45'
              variants={b.getVariants(undefined)}
              container={true}
              direction={'column'}
              alignItems={'flex-start'}
              rowSpacing={1.5}
              data-d={getKey(rs, '17c901e62ff14c88a0033293')}
            >
              <Grid
                key='grid-46'
                variants={b.getVariants(undefined)}
                direction={'column'}
                container={true}
                item={true}
                justifyContent={'flex-start'}
                data-d={getKey(rs, '17c901e62ff14c88a0033294')}
              >
                <Grid
                  key='grid-47'
                  variants={b.getVariants(undefined)}
                  item={true}
                  data-d={getKey(rs, '17c901e62ff14c88a0033295')}
                >
                  <Typography
                    key='typography-13'
                    variants={b.getVariants(undefined)}
                    sx={{
                      pb: 0.5,
                      fontSize: 18,
                      fontWeight: '400',
                      lineHeight: 1.25,
                    }}
                    data-d={getKey(rs, '17c901e62ff14c88a0033296')}
                  >
                    <Text
                      key='default-text-60'
                      variants={b.getVariants(undefined)}
                      className={b.getUniqueClassName()}
                      style={undefined}
                      text={'DayLuna Human Design Podcast'}
                      data-d={getKey(rs, '17c901e62ff14c88a0033297')}
                    />
                  </Typography>
                </Grid>
                <Grid
                  key='grid-63'
                  variants={b.getVariants(undefined)}
                  item={true}
                  container={true}
                  justifyContent={'space-between'}
                  data-d={getKey(rs, '17c901e62ff14c88a003329f')}
                >
                  <Grid
                    key='grid-64'
                    variants={b.getVariants(undefined)}
                    item={true}
                    data-d={getKey(rs, '17c901e62ff14c88a00332a0')}
                  >
                    <Typography
                      key='typography-18'
                      variants={b.getVariants(undefined)}
                      variant={'subtitle2'}
                      sx={{
                        color: 'grey.700',
                        pb: 1,
                      }}
                      data-d={getKey(rs, '17c901e62ff14c88a00332a1')}
                    >
                      <Text
                        key='default-text-63'
                        variants={b.getVariants(undefined)}
                        className={b.getUniqueClassName()}
                        style={undefined}
                        text={'DayLuna'}
                        data-d={getKey(rs, '17c901e62ff14c88a00332a2')}
                      />
                    </Typography>
                  </Grid>
                </Grid>
                <Grid
                  key='grid-48'
                  variants={b.getVariants(undefined)}
                  container={true}
                  direction={'row'}
                  spacing={undefined}
                  justifyContent={'space-between'}
                  alignItems={'center'}
                  rowSpacing={1}
                  data-d={getKey(rs, '17c901e62ff14c88a0033298')}
                >
                  <Grid
                    key='grid-49'
                    variants={b.getVariants(undefined)}
                    item={true}
                    data-d={getKey(rs, '17c901e62ff14c88a0033299')}
                  >
                    <Chip
                      key='chip-2'
                      variants={b.getVariants(undefined)}
                      label={'Human Design'}
                      size={'small'}
                      color={undefined}
                      data-d={getKey(rs, '17c901e62ff14c88a003329a')}
                    />
                  </Grid>
                </Grid>
              </Grid>
              <Grid
                key='grid-66'
                variants={b.getVariants(undefined)}
                container={true}
                direction={'column'}
                item={true}
                data-d={getKey(rs, '17c901e62ff14c88a00332a6')}
              >
                <Grid
                  key='grid-67'
                  variants={b.getVariants(undefined)}
                  container={true}
                  item={true}
                  data-d={getKey(rs, '17c901e62ff14c88a00332a7')}
                >
                  <Typography
                    key='typography-52'
                    variants={b.getVariants(undefined)}
                    variant={'body2'}
                    data-d={getKey(rs, '17c901e62ff14c88a00332a8')}
                  >
                    <Text
                      key='default-text-108'
                      variants={b.getVariants(undefined)}
                      className={b.mClassnames([
                        b.getUniqueClassName(),
                        styles['clutchClass12062'],
                      ])}
                      text={'We dive deep into Authorities, Strategies, Profiles and the New Paradigm as well as host live readings for special guests and get into the intricacies of parenting and so much more with Human Design. Discover how Human Design can transform your life and what you can start doing TODAY to start living in alignment.'}
                      tag={'span'}
                      data-d={getKey(rs, '17c901e62ff14c88a00332a9')}
                    />
                  </Typography>
                </Grid>
              </Grid>
            </Grid>
          </CardContent>
        </CardActionArea>
        <CardActions
          key='card-actions-11'
          variants={b.getVariants(undefined)}
          data-d={getKey(rs, '17c901e62fe14c88a0033286')}
        >
          <Grid
            key='grid-59'
            variants={b.getVariants(undefined)}
            container={true}
            data-d={getKey(rs, '17c901e62fe14c88a0033287')}
          >
            <Grid
              key='grid-60'
              variants={b.getVariants(undefined)}
              container={true}
              justifyContent={'space-between'}
              alignItems={'center'}
              data-d={getKey(rs, '17c901e62fe14c88a0033288')}
            >
              <Box
                key='box-31'
                variants={b.getVariants(undefined)}
                sx={{
                  display: 'flex',
                  alignItems: 'center',
                }}
                data-d={getKey(rs, '17c901e62fe14c88a0033289')}
              >
                <State
                  key='number-state-11'
                  variants={b.getVariants(undefined)}
                  initialValue={4.65}
                  data-d={getKey(rs, '17c901e62fe14c88a003328a')}
                >
                  {((r, v) => (...numberstate11Args) => {
                    const newVariables = {};
                  
                    let variables = {
                      ...v,
                      ...newVariables
                    };
                  
                    const rs = report(r, '17c901e62fe14c88a003328a', '178bf970a34fae252001bf06', numberstate11Args, newVariables);
                  
                    const renderFn = [
                      <Rating
                        key='rating-11'
                        variants={b.getVariants(undefined)}
                        size={'small'}
                        readOnly={true}
                        value={4.65}
                        precision={0.25}
                        data-d={getKey(rs, '17c901e62fe14c88a003328b')}
                      />,
                      <Box
                        key='box-32'
                        variants={b.getVariants(undefined)}
                        data-d={getKey(rs, '17c901e62ff14c88a003328c')}
                      >
                        <Typography
                          key='typography-51'
                          variants={b.getVariants(undefined)}
                          variant={'caption'}
                          sx={{
                            fontSize: '11px',
                            pl: 0.5,
                          }}
                          data-d={getKey(rs, '17c901e62ff14c88a003328d')}
                        >
                          <Text
                            key='default-text-106'
                            variants={b.getVariants(undefined)}
                            className={b.getUniqueClassName()}
                            style={undefined}
                            text={b.tryCatch(() => ('(' + b.propertyBind(numberstate11Args, ['0','state']) + ')'))}
                            tag={false}
                            data-d={getKey(rs, '17c901e62ff14c88a003328e')}
                          />
                        </Typography>
                      </Box>
                    ];
                  
                    return typeof renderFn === 'function' ? renderFn(...numberstate11Args) : renderFn;
                  })(rs, variables)}
                </State>
              </Box>
              <Button
                key='button-23'
                variants={b.getVariants(undefined)}
                variant={'text'}
                size={'small'}
                data-d={getKey(rs, '17c901e62ff14c88a003328f')}
              >
                <Text
                  key='default-text-107'
                  variants={b.getVariants(undefined)}
                  className={b.getUniqueClassName()}
                  style={{
                    textTransform: 'capitalize',
                  }}
                  text={'Learn More'}
                  tag={'span'}
                  data-d={getKey(rs, '17c901e62ff14c88a0033290')}
                />
              </Button>
            </Grid>
          </Grid>
        </CardActions>
      </Card>
    ]);
  };
  ;
